* For Transformer-> Read File/ Preprocess Part1/ Preprocessing Add Features/ Preprocessing Part2_transformer
* For XGboost-> Read File/ Preprocess Part1/ Preprocessing Add Features/ Preprocessing Part3_XGboost

## Read File

In [ ]:
#for google drive
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

In [ ]:
from pathlib import Path
import pandas as pd

TRAIN_DIR = '/content/gdrive/MyDrive/Fintech'
ccba = pd.read_csv('/content/gdrive/MyDrive/Fintech/esun_dataset/public_train_x_ccba_full_hashed.csv')
cinfo = pd.read_csv('/content/gdrive/MyDrive/Fintech/esun_dataset/public_train_x_custinfo_full_hashed.csv')
cdtx = pd.read_csv('/content/gdrive/MyDrive/Fintech/esun_dataset/public_train_x_cdtx0001_full_hashed.csv')
remit = pd.read_csv('/content/gdrive/MyDrive/Fintech/esun_dataset/public_train_x_remit1_full_hashed.csv')
dp = pd.read_csv('/content/gdrive/MyDrive/Fintech/esun_dataset/public_train_x_dp_full_hashed.csv')
pdate = pd.read_csv('/content/gdrive/MyDrive/Fintech/esun_dataset/train_x_alert_date.csv')
tdate = pd.read_csv('/content/gdrive/MyDrive/Fintech/esun_dataset/public_x_alert_date.csv')
answer = pd.read_csv('/content/gdrive/MyDrive/Fintech/esun_dataset/train_y_answer.csv')
sample = pd.read_csv('/content/gdrive/MyDrive/Fintech/esun_dataset/預測的案件名單及提交檔案範例.csv')


# ccba = pd.read_csv('/content/gdrive/MyDrive/Fintech/esun_dataset/private_x_ccba_full_hashed.csv')
# cinfo = pd.read_csv('/content/gdrive/MyDrive/Fintech/esun_dataset/private_x_custinfo_full_hashed.csv')
# cdtx = pd.read_csv('/content/gdrive/MyDrive/Fintech/esun_dataset/private_x_cdtx0001_full_hashed.csv')
# remit = pd.read_csv('/content/gdrive/MyDrive/Fintech/esun_dataset/private_x_remit1_full_hashed.csv')
# dp = pd.read_csv('/content/gdrive/MyDrive/Fintech/esun_dataset/private_x_dp_full_hashed.csv')
# pdate = pd.read_csv('/content/gdrive/MyDrive/Fintech/esun_dataset/train_x_alert_date.csv')
# tdate = pd.read_csv('/content/gdrive/MyDrive/Fintech/esun_dataset/private_x_alert_date.csv')
# answer = pd.read_csv('/content/gdrive/MyDrive/Fintech/esun_dataset/train_y_answer.csv')
# sample = pd.read_csv('/content/gdrive/MyDrive/Fintech/esun_dataset/預測的案件名單及提交檔案範例.csv')

In [ ]:
dp.head()

,cust_id,debit_credit,tx_date,tx_time,tx_type,tx_amt,exchg_rate,info_asset_code,fiscTxId,txbranch,cross_bank,ATM
0,01a8178d33352121442d06aa93215fcf48032efc331235...,CR,398,13,2,288222.0,1.000,6,NaN,NaN,0,0
1,01b1735c3dbf0a35c1c989bb45434ce4326b365b73db06...,CR,400,12,2,8544.0,1.000,6,NaN,NaN,0,0
2,01b1735c3dbf0a35c1c989bb45434ce4326b365b73db06...,CR,425,11,2,258.0,29.055,20,NaN,NaN,0,1
3,01b1735c3dbf0a35c1c989bb45434ce4326b365b73db06...,DB,403,13,2,804.0,29.780,20,NaN,NaN,0,1
4,01b1735c3dbf0a35c1c989bb45434ce4326b365b73db06...,CR,419,17,2,938.0,1.000,12,NaN,NaN,0,0

## Generate Report(不用執行)

In [ ]:
##install pandas_profiling for ProfileReport->minimal (Colab need)
!pip install -U https://github.com/pandas-profiling/pandas-profiling/archive/master.zip
!pip install -U pandas-profiling

import pandas_profiling as pp
from pandas_profiling import ProfileReport

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting https://github.com/pandas-profiling/pandas-profiling/archive/master.zip
  Downloading https://github.com/pandas-profiling/pandas-profiling/archive/master.zip
     - 22.0 MB 163 kB/s
Requirement already satisfied: scipy<1.10,>=1.4.1 in /usr/local/lib/python3.8/dist-packages (from pandas-profiling===dev) (1.7.3)
Requirement already satisfied: pandas!=1.4.0,<1.6,>1.1 in /usr/local/lib/python3.8/dist-packages (from pandas-profiling===dev) (1.3.5)
Requirement already satisfied: matplotlib<3.7,>=3.2 in /usr/local/lib/python3.8/dist-packages (from pandas-profiling===dev) (3.2.2)
Requirement already satisfied: pydantic<1.11,>=1.8.1 in /usr/local/lib/python3.8/dist-packages (from pandas-profiling===dev) (1.10.2)
Requirement already satisfied: PyYAML<6.1,>=5.0.0 in /usr/local/lib/python3.8/dist-packages (from pandas-profiling===dev) (6.0)
Requirement already satisfied: jinja2<3.2,>=2.11.1 in /usr/local/lib/python3.8/dist-packages (from pandas-profiling===dev) (2.11.3)
Collecting visions[type_image_path]==0.7.5
  Downloading visions-0.7.5-py3-none-any.whl (102 kB)
     |████████████████████████████████| 102 kB 6.8 MB/s
Requirement already satisfied: numpy<1.24,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pandas-profiling===dev) (1.21.6)
Collecting htmlmin==0.1.12
  Downloading htmlmin-0.1.12.tar.gz (19 kB)
Collecting phik<0.13,>=0.11.1
  Downloading phik-0.12.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (679 kB)
     |████████████████████████████████| 679 kB 50.5 MB/s
Collecting requests<2.29,>=2.24.0
  Downloading requests-2.28.1-py3-none-any.whl (62 kB)
     |████████████████████████████████| 62 kB 1.9 MB/s
Requirement already satisfied: tqdm<4.65,>=4.48.2 in /usr/local/lib/python3.8/dist-packages (from pandas-profiling===dev) (4.64.1)
Requirement already satisfied: seaborn<0.13,>=0.10.1 in /usr/local/lib/python3.8/dist-packages (from pandas-profiling===dev) (0.11.2)
Collecting multimethod<1.10,>=1.4
  Downloading multimethod-1.9-py3-none-any.whl (10 kB)
Collecting statsmodels<0.14,>=0.13.2
  Downloading statsmodels-0.13.5-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (9.9 MB)
     |████████████████████████████████| 9.9 MB 44.8 MB/s
Collecting typeguard<2.14,>=2.13.2
  Downloading typeguard-2.13.3-py3-none-any.whl (17 kB)
Requirement already satisfied: networkx>=2.4 in /usr/local/lib/python3.8/dist-packages (from visions[type_image_path]==0.7.5->pandas-profiling===dev) (2.8.8)
Collecting tangled-up-in-unicode>=0.0.4
  Downloading tangled_up_in_unicode-0.2.0-py3-none-any.whl (4.7 MB)
     |████████████████████████████████| 4.7 MB 39.2 MB/s
Requirement already satisfied: attrs>=19.3.0 in /usr/local/lib/python3.8/dist-packages (from visions[type_image_path]==0.7.5->pandas-profiling===dev) (22.1.0)
Requirement already satisfied: Pillow in /usr/local/lib/python3.8/dist-packages (from visions[type_image_path]==0.7.5->pandas-profiling===dev) (7.1.2)
Collecting imagehash
  Downloading ImageHash-4.3.1-py2.py3-none-any.whl (296 kB)
     |████████████████████████████████| 296 kB 56.1 MB/s
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.8/dist-packages (from jinja2<3.2,>=2.11.1->pandas-profiling===dev) (2.0.1)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.8/dist-packages (from matplotlib<3.7,>=3.2->pandas-profiling===dev) (2.8.2)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.8/dist-packages (from matplotlib<3.7,>=3.2->pandas-profiling===dev) (3.0.9)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.8/dist-packages (from matplotlib<3.7,>=3.2->pandas-profiling===dev) (0.11.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.8/dist-packages (from matplotlib<3.7,>=3.2->pandas-profiling===dev) (1.4.4)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.8/dist-packages (from pandas!=1.4.0,<1.6,>1.1->pandas-profiling===dev) (2022.6)
Requirement already satisfied: joblib>=0.14.1 in /usr/local/lib/python3.8/dist-packages (from phik<0.13,>=0.11.1->pandas-profiling===dev) (1.2.0)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.8/dist-packages (from pydantic<1.11,>=1.8.1->pandas-profiling===dev) (4.4.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.1->matplotlib<3.7,>=3.2->pandas-profiling===dev) (1.15.0)
Requirement already satisfied: charset-normalizer<3,>=2 in /usr/local/lib/python3.8/dist-packages (from requests<2.29,>=2.24.0->pandas-profiling===dev) (2.1.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests<2.29,>=2.24.0->pandas-profiling===dev) (1.24.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests<2.29,>=2.24.0->pandas-profiling===dev) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests<2.29,>=2.24.0->pandas-profiling===dev) (2022.9.24)
Requirement already satisfied: patsy>=0.5.2 in /usr/local/lib/python3.8/dist-packages (from statsmodels<0.14,>=0.13.2->pandas-profiling===dev) (0.5.3)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.8/dist-packages (from statsmodels<0.14,>=0.13.2->pandas-profiling===dev) (21.3)
Requirement already satisfied: PyWavelets in /usr/local/lib/python3.8/dist-packages (from imagehash->visions[type_image_path]==0.7.5->pandas-profiling===dev) (1.4.1)
Building wheels for collected packages: pandas-profiling, htmlmin
  Building wheel for pandas-profiling (setup.py) ... done
  Created wheel for pandas-profiling: filename=pandas_profiling-dev-py2.py3-none-any.whl size=324949 sha256=990c5e4106f06f6885c035d4e50a180d1d58c3b88a7a16c5295285139dadb300
  Stored in directory: /tmp/pip-ephem-wheel-cache-0i2xkev1/wheels/64/b6/85/dfc808b23666a5910371784e349d28818006ff63ed9cfeca59
  WARNING: Built wheel for pandas-profiling is invalid: Metadata 1.2 mandates PEP 440 version, but 'dev' is not
  Building wheel for htmlmin (setup.py) ... done
  Created wheel for htmlmin: filename=htmlmin-0.1.12-py3-none-any.whl size=27098 sha256=75efd1def269a0ea4de37d917c9b2b1e8287dc87683f5b225629c220a1200a9a
  Stored in directory: /root/.cache/pip/wheels/23/14/6e/4be5bfeeb027f4939a01764b48edd5996acf574b0913fe5243
Successfully built htmlmin
Failed to build pandas-profiling
Installing collected packages: tangled-up-in-unicode, multimethod, visions, imagehash, typeguard, statsmodels, requests, phik, htmlmin, pandas-profiling
  Attempting uninstall: typeguard
    Found existing installation: typeguard 2.7.1
    Uninstalling typeguard-2.7.1:
      Successfully uninstalled typeguard-2.7.1
  Attempting uninstall: statsmodels
    Found existing installation: statsmodels 0.12.2
    Uninstalling statsmodels-0.12.2:
      Successfully uninstalled statsmodels-0.12.2
  Attempting uninstall: requests
    Found existing installation: requests 2.23.0
    Uninstalling requests-2.23.0:
      Successfully uninstalled requests-2.23.0
  Attempting uninstall: pandas-profiling
    Found existing installation: pandas-profiling 1.4.1
    Uninstalling pandas-profiling-1.4.1:
      Successfully uninstalled pandas-profiling-1.4.1
    Running setup.py install for pandas-profiling ... canceled
ERROR: Operation cancelled by user
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/cli/base_command.py", line 180, in _main
    status = self.run(options, args)
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/cli/req_command.py", line 199, in wrapper
    return func(self, options, args)
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/commands/install.py", line 393, in run
    installed = install_given_reqs(
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/req/__init__.py", line 77, in install_given_reqs
    requirement.install(
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/req/req_install.py", line 811, in install
    success = install_legacy(
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/operations/install/legacy.py", line 69, in install
    runner(
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/utils/subprocess.py", line 274, in runner
    call_subprocess(
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/utils/subprocess.py", line 194, in call_subprocess
    line = proc.stdout.readline()  # type: str
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/cli/main.py", line 71, in main
    return command.main(cmd_args)
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/cli/base_command.py", line 104, in main
    return self._main(args)
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/cli/base_command.py", line 213, in _main
    logger.debug("Exception information:", exc_info=True)
  File "/usr/lib/python3.8/logging/__init__.py", line 1434, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/usr/lib/python3.8/logging/__init__.py", line 1589, in _log
    self.handle(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 954, in handle
    self.emit(record)
  File "/usr/lib/python3.8/logging/handlers.py", line 71, in emit
    logging.FileHandler.emit(self, record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1187, in emit
    StreamHandler.emit(self, record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/utils/logging.py", line 130, in format
    formatted = super().format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 676, in format
    record.exc_text = self.formatException(record.exc_info)
  File "/usr/lib/python3.8/logging/__init__.py", line 626, in formatException
    traceback.print_exception(ei[0], ei[1], tb, None, sio)
  File "/usr/lib/python3.8/traceback.py", line 103, in print_exception
    for line in TracebackException(
  File "/usr/lib/python3.8/traceback.py", line 508, in __init__
    self.stack = StackSummary.extract(
  File "/usr/lib/python3.8/traceback.py", line 366, in extract
    f.line
  File "/usr/lib/python3.8/traceback.py", line 288, in line
    self._line = linecache.getline(self.filename, self.lineno).strip()
  File "/usr/lib/python3.8/linecache.py", line 16, in getline
    lines = getlines(filename, module_globals)
  File "/usr/lib/python3.8/linecache.py", line 47, in getlines
    return updatecache(filename, module_globals)
  File "/usr/lib/python3.8/linecache.py", line 136, in updatecache
    with tokenize.open(fullname) as fp:
  File "/usr/lib/python3.8/tokenize.py", line 394, in open
    encoding, lines = detect_encoding(buffer.readline)
  File "/usr/lib/python3.8/tokenize.py", line 363, in detect_encoding
    first = read_or_stop()
  File "/usr/lib/python3.8/tokenize.py", line 321, in read_or_stop
    return readline()
KeyboardInterrupt
^C
Traceback (most recent call last):
  File "<frozen importlib._bootstrap_external>", line 148, in _path_is_mode_type
  File "<frozen importlib._bootstrap_external>", line 142, in _path_stat
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/dist-packages/sphinxcontrib/__init__.abi3.so'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 5, in <module>
    from pip._internal.cli.main import main
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/cli/main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/cli/main_parser.py", line 8, in <module>
    from pip._internal.cli import cmdoptions
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/cli/cmdoptions.py", line 23, in <module>
    from pip._internal.cli.parser import ConfigOptionParser
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/cli/parser.py", line 12, in <module>
    from pip._internal.configuration import Configuration, ConfigurationError
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/configuration.py", line 21, in <module>
    from pip._internal.exceptions import (
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/exceptions.py", line 7, in <module>
    from pip._vendor.pkg_resources import Distribution
  File "/usr/local/lib/python3.8/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 3252, in <module>
    def _initialize_master_working_set():
  File "/usr/local/lib/python3.8/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 3277, in _initialize_master_working_set
    tuple(
  File "/usr/local/lib/python3.8/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 3278, in <genexpr>
    dist.activate(replace=False)
  File "/usr/local/lib/python3.8/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 2782, in activate
    fixup_namespace_packages(self.location)
  File "/usr/local/lib/python3.8/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 2295, in fixup_namespace_packages
    subpath = _handle_ns(package, path_item)
  File "/usr/local/lib/python3.8/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 2201, in _handle_ns
    loader = importer.find_module(packageName)
  File "<frozen importlib._bootstrap_external>", line 546, in _find_module_shim
  File "<frozen importlib._bootstrap_external>", line 1488, in find_loader
  File "<frozen importlib._bootstrap_external>", line 1525, in find_spec
  File "<frozen importlib._bootstrap_external>", line 156, in _path_isfile
  File "<frozen importlib._bootstrap_external>", line 148, in _path_is_mode_type
KeyboardInterrupt
^C

ModuleNotFoundError: ignored

In [ ]:
names = ['ccba', 'cdtx', 'custinfo', 'dp', 'remit', 'pdate', 'tdate', 'answer', 'sample']
datas = [ccba, cdtx, cinfo, dp, remit, pdate, tdate, answer, sample]
num_files = len(datas)

for i in range(num_files):
    print(f'{names[i]}: {datas[i].shape}')
    profile = ProfileReport(datas[i], minimal=True, title=names[i])
    profile.to_file(f'{TRAIN_DIR}/data_report/{names[i]}.html', )

## Preprocess Part1

In [ ]:
import pickle

from sklearn.preprocessing import QuantileTransformer
import numpy as np
from easydict import EasyDict as edict
import pandas as pd
from tqdm import tqdm
from random import choice

### Change Type
reduce size

In [ ]:
#cinfo
cinfo["risk_rank"] = cinfo["risk_rank"].astype("int8")
#cinfo["occupation_code"] = cinfo["occupation_code"].astype("int8", copy=False)
cinfo["AGE"] = cinfo["AGE"].astype("int8")
#dp
dp['tx_type'] = dp["tx_type"].astype("int8")
dp['info_asset_code'] = dp["info_asset_code"].astype("int8")
dp['cross_bank'] = dp["cross_bank"].astype("int8")
dp['ATM'] = dp["ATM"].astype("int8")

#remit
remit['trans_no'] = remit["trans_no"].astype("int8")

#cdtx
cdtx['country'] = cdtx["country"].astype("int16")
cdtx['cur_type'] = cdtx["cur_type"].astype("int8")

### Missing Value
* ISNULL
* cinfo->occupation_code (group by riskrank+age frequecey)
* dp->tx_amt/fiscTxId/txbranch (group by customer id median/frequecey/frequecey)

In [ ]:
len(cinfo["occupation_code"])

2005

In [ ]:
dp.isnull().sum()

cust_id                0
debit_credit           0
tx_date                0
tx_time                0
tx_type                0
tx_amt               634
exchg_rate             0
info_asset_code        0
fiscTxId           19464
txbranch           18164
cross_bank             0
ATM                    0
dtype: int64

In [ ]:
##add new feature
def map_stat_feature(X, b, c, mean=True, max_val=True, min_val=True, std=True, var=True, median=True, median_diff=True):
    # b groupby c mean...
    if(mean):
        X[b + '_' + c + '_mean'] = X[c].map(X.loc[:, [b, c]].groupby(c).mean().loc[:, b].to_dict())
    if(max_val):
        X[b + '_' + c + '_max'] = X[c].map(X.loc[:, [b, c]].groupby(c).max().loc[:, b].to_dict())
    if(min_val):
        X[b + '_' + c + '_min'] = X[c].map(X.loc[:, [b, c]].groupby(c).min().loc[:, b].to_dict())
    if(std):
        X[b + '_' + c + '_std'] = X[c].map(X.loc[:, [b, c]].groupby(c).std().loc[:, b].to_dict())
    if(var):
        X[b + '_' + c + '_var'] = X[b + '_' + c + '_std'] ** 2
    if(median):
        X[b + '_' + c + '_median'] = X[c].map(X.loc[:, [b, c]].groupby(c).median().loc[:, b].to_dict())
    if(median_diff):
        X[b + '_' + c + '_median_diff'] = X[b] - X[b + '_' + c + '_median']
    return None

def map_stat_feature_cata(X, b, c,mode = True):
    # b groupby c mode...
    #可能有兩個mode選最後一個
    if(mode):
        # s = X.groupby(c)[b].agg(pd.Series.mode)
        # print(s)
        s = X.groupby(c).agg({"x": [lambda s: pd.Series.mode(b).iloc[0], "sum"]})
        s = s.str[-1].fillna(s.mask(s.str.len().eq(0)))
        X[b + '_' + c + '_mode'] = X[c].map(s.to_dict())
    return None

def map_stat_feature_cata_2(X, b, c,mode = True):
    # b groupby c mode...
    # if c only one
    if(mode):
        X[b + '_' + c + '_mode'] = X[c].map(X.groupby(c)[b].agg(pd.Series.mode).to_dict())
    return None

def map_stat_feature_cata_multi(X, b, c,mode = True):
    # c->multi columns
    # b groupby c mode...
    modes = X.groupby(c).apply(pd.DataFrame.mode).reset_index(drop=True)
    modes = modes[modes[c[0]].notna()]
    modes = modes[modes[c[1]].notna()]
    c_2 = c.copy()
    c_2.append(b)
    X = pd.merge(X, modes.loc[:, c_2], on=c, how='left')
    return X

def fillna_with_col(X,b,c):
    X[b].fillna(value=X[c], inplace=True)
    return None

In [ ]:
##處理dp缺失值
#合併dp+custinfo
print(dp.shape)
cinfo_tmp = cinfo[['cust_id','risk_rank']].drop_duplicates(keep='last').drop_duplicates(['cust_id'],keep='last')
print(cinfo_tmp.head())
dp = pd.merge(dp,cinfo_tmp,on=['cust_id'], how='left')
del cinfo_tmp
dp.head()

(45071, 12)
                                             cust_id  risk_rank
1  7ad6b2889c6d0b906d73a5012f429a831f2d6f996bba26...          1
2  252117094a387944f2d8aea76ca95fd927064bdaf72e1c...          1
3  0585831d57313ede3fa11841dc488df3d5080e7b03c49a...          1
4  9b91812ca1771f5c7ead09f8be19c6a373f03be9a1fceb...          1
8  e8d5a2092c203446e10592fe7acbec03f0ca643536cafb...          1

,cust_id,debit_credit,tx_date,tx_time,tx_type,tx_amt,exchg_rate,info_asset_code,fiscTxId,txbranch,cross_bank,ATM,risk_rank
0,01a8178d33352121442d06aa93215fcf48032efc331235...,CR,398,13,2,288222.0,1.000,6,NaN,NaN,0,0,1
1,01b1735c3dbf0a35c1c989bb45434ce4326b365b73db06...,CR,400,12,2,8544.0,1.000,6,NaN,NaN,0,0,3
2,01b1735c3dbf0a35c1c989bb45434ce4326b365b73db06...,CR,425,11,2,258.0,29.055,20,NaN,NaN,0,1,3
3,01b1735c3dbf0a35c1c989bb45434ce4326b365b73db06...,DB,403,13,2,804.0,29.780,20,NaN,NaN,0,1,3
4,01b1735c3dbf0a35c1c989bb45434ce4326b365b73db06...,CR,419,17,2,938.0,1.000,12,NaN,NaN,0,0,3

In [ ]:
map_stat_feature(dp, 'tx_amt', 'cust_id', mean=False, max_val=False, min_val=False, std=False, var=False, median=True, median_diff=False)
map_stat_feature(dp, 'tx_amt', 'risk_rank', mean=False, max_val=False, min_val=False, std=False, var=False, median=True, median_diff=False)
map_stat_feature_cata(dp, 'txbranch', 'cust_id', mode=True)
map_stat_feature_cata_2(dp, 'txbranch', 'risk_rank', mode=True)
map_stat_feature_cata(dp, 'fiscTxId', 'cust_id', mode=True)
map_stat_feature_cata_2(dp, 'fiscTxId', 'risk_rank', mode=True)

In [ ]:
fillna_with_col(dp,'tx_amt','tx_amt_cust_id_median')
fillna_with_col(dp,'tx_amt','tx_amt_risk_rank_median')
fillna_with_col(dp,'fiscTxId','fiscTxId_cust_id_mode')
fillna_with_col(dp,'fiscTxId','fiscTxId_risk_rank_mode')
fillna_with_col(dp,'txbranch','txbranch_cust_id_mode')
fillna_with_col(dp,'txbranch','txbranch_risk_rank_mode')
dp.isnull().sum()

cust_id                      0
debit_credit                 0
tx_date                      0
tx_time                      0
tx_type                      0
tx_amt                       0
exchg_rate                   0
info_asset_code              0
fiscTxId                     0
txbranch                     0
cross_bank                   0
ATM                          0
risk_rank                    0
tx_amt_cust_id_median      561
tx_amt_risk_rank_median      0
txbranch_risk_rank_mode      0
fiscTxId_risk_rank_mode      0
dtype: int64

In [ ]:
#cinfo 缺失值處理
#dp.isnull().sum()
dp['fiscTxId'].value_counts()

4.0     38238
7.0      2397
21.0     1945
20.0     1255
3.0       534
22.0      333
6.0        89
0.0        74
2.0        74
5.0        73
28.0       24
16.0        9
13.0        8
23.0        8
18.0        3
1.0         2
26.0        2
9.0         2
15.0        1
Name: fiscTxId, dtype: int64

In [ ]:
cinfo = map_stat_feature_cata_multi(cinfo, 'occupation_code', ['risk_rank','AGE'], mode=True)
fillna_with_col(cinfo,'occupation_code_x','occupation_code_y')
cinfo.isnull().sum()

alert_key            0
cust_id              0
risk_rank            0
occupation_code_x    0
total_asset          0
AGE                  0
occupation_code_y    0
dtype: int64

In [ ]:
#check length
print(cinfo.shape)
print(dp.shape)

In [ ]:
#check null value
print(cinfo.isnull().sum())
print(dp.isnull().sum())

In [ ]:
#check 空值
# tmp_col_name = ['tx_amt','fiscTxId', 'txbranch']
# for col in tmp_col_name:
#     for k in range(dp.shape[0]):
#         if type(dp.loc[k,col])== np.ndarray:
#             print(dp.loc[k,col])

In [ ]:
cinfo.rename(columns={'occupation_code_x':'occupation_code'}, inplace=True)

In [ ]:
#cinfo = cinfo.drop(columns=['occupation_code_y'])
#dp = dp.drop(columns=['risk_rank','tx_amt_cust_id_median', 'tx_amt_risk_rank_median','fiscTxId_cust_id_mode','fiscTxId_risk_rank_mode','txbranch_cust_id_mode','txbranch_risk_rank_mode'])
dp = dp.drop(columns=['risk_rank','tx_amt_cust_id_median', 'tx_amt_risk_rank_median','fiscTxId_risk_rank_mode','txbranch_risk_rank_mode'])

In [ ]:
cinfo["occupation_code"] = cinfo["occupation_code"].astype("int8", copy=False)
dp['txbranch'] = dp["txbranch"].astype("int16")
dp['fiscTxId'] = dp["fiscTxId"].astype("int8")

In [ ]:
cinfo.head()

In [ ]:
dp.head(20000)

##Preprocessing Add Features
* Group by customer_id time diff cdtx/remit/dp
* - cdtx: amt group by country/cur type
  - dp: txx_amt group by tx_type/info_asset_code/fiscTxId/txbranch
  - remit: trade_amount_usd group by trans_no

###Group by customer_id time diff cdtx/remit/dp

In [ ]:
#for cdtx, remit
def add_date_diff(X,b,c):
    X = X.sort_values(by=[b], ascending=True)
    #group by c count b diff
    X[b + '_' + c + '_diff'] = X.groupby(c)[b].diff().fillna(0).astype("int16")
    return X

#for dp
def add_time_diff(X,b,c):
    X = X.sort_values(by=[i for i in b], ascending=True)
    X['tmp'] = X[b[0]]*24+X[b[1]]
    #group by c count b diff
    X['tx_time_' + c + '_diff'] = X.groupby(c)['tmp'].diff().fillna(0).astype("int16")
    X = X.drop(columns=['tmp'])
    return X

In [ ]:
cdtx = add_date_diff(cdtx,'date','cust_id')
remit = add_date_diff(remit,'trans_date','cust_id')
dp = add_time_diff(dp,['tx_date','tx_time'],'cust_id')

In [ ]:
#交易平均時間差
map_stat_feature(cdtx, 'date_cust_id_diff', 'cust_id', mean=True, max_val=False, min_val=False, std=False, var=False, median=False, median_diff=False)
map_stat_feature(remit, 'trans_date_cust_id_diff', 'cust_id', mean=True, max_val=False, min_val=False, std=False, var=False, median=False, median_diff=False)
map_stat_feature(dp, 'tx_time_cust_id_diff', 'cust_id', mean=True, max_val=False, min_val=False, std=False, var=False, median=False, median_diff=False)

In [ ]:
#for test
#dp[dp['cust_id']=='4220624de6d38bd4b41d1c32932e03f3c0e85b1b08b7e399df191feb73d3a4c1'].tail(50)
dp.head()

,cust_id,debit_credit,tx_date,tx_time,tx_type,tx_amt,exchg_rate,info_asset_code,fiscTxId,txbranch,cross_bank,ATM,tx_time_cust_id_diff,tx_time_cust_id_diff_cust_id_mean
9732,01c705b457297805c1c08137cb3adb164b8f393c265db2...,CR,395,0,2,3062.0,1.0,13,4,140,1,1,0,0.06991
9736,01c705b457297805c1c08137cb3adb164b8f393c265db2...,CR,395,0,2,510.0,1.0,13,4,140,1,1,0,0.06991
9802,01c705b457297805c1c08137cb3adb164b8f393c265db2...,CR,395,0,2,7161.0,1.0,13,4,313,1,1,0,0.06991
9816,01c705b457297805c1c08137cb3adb164b8f393c265db2...,CR,395,0,2,1021.0,1.0,13,4,307,1,1,0,0.06991
9830,01c705b457297805c1c08137cb3adb164b8f393c265db2...,CR,395,0,2,510.0,1.0,13,4,310,1,1,0,0.06991

###dp new feature
* tx_amt*exchg_rate
* is_foreign(exchg_rate!=1)

In [ ]:
dp['tx_amt_exchg'] = dp['tx_amt']*dp['exchg_rate']
dp['is_foreign'] = dp['exchg_rate']!=1

In [ ]:
dp['is_foreign'].value_counts()

False    38123
True      6948
Name: is_foreign, dtype: int64

### stat_feature for amt

In [ ]:
# cdtx: amt group by country/cur type
# dp: txx_amt group by tx_type/info_asset_code/fiscTxId/txbranch
# remit: trade_amount_usd group by trans_no

map_stat_feature(cdtx, 'amt', 'country', mean=True, max_val=True, min_val=True, std=True, var=True, median=True, median_diff=True)
map_stat_feature(cdtx, 'amt', 'cur_type', mean=True, max_val=True, min_val=True, std=True, var=True, median=True, median_diff=True)
map_stat_feature(dp, 'tx_amt_exchg', 'tx_type', mean=True, max_val=True, min_val=True, std=True, var=True, median=True, median_diff=True)
map_stat_feature(dp, 'tx_amt_exchg', 'info_asset_code', mean=True, max_val=True, min_val=True, std=True, var=True, median=True, median_diff=True)
map_stat_feature(dp, 'tx_amt_exchg', 'fiscTxId', mean=True, max_val=True, min_val=True, std=True, var=True, median=True, median_diff=True)
map_stat_feature(dp, 'tx_amt_exchg', 'txbranch', mean=True, max_val=True, min_val=True, std=True, var=True, median=True, median_diff=True)
map_stat_feature(remit, 'trade_amount_usd', 'trans_no', mean=True, max_val=True, min_val=True, std=True, var=True, median=True, median_diff=True)

In [ ]:
cdtx.columns

Index(['cust_id', 'date', 'country', 'cur_type', 'amt', 'date_cust_id_diff',
       'date_cust_id_diff_cust_id_mean', 'amt_country_mean', 'amt_country_max',
       'amt_country_min', 'amt_country_std', 'amt_country_var',
       'amt_country_median', 'amt_country_median_diff', 'amt_cur_type_mean',
       'amt_cur_type_max', 'amt_cur_type_min', 'amt_cur_type_std',
       'amt_cur_type_var', 'amt_cur_type_median', 'amt_cur_type_median_diff'],
      dtype='object')

In [ ]:
dp.columns

Index(['cust_id', 'debit_credit', 'tx_date', 'tx_time', 'tx_type', 'tx_amt',
       'exchg_rate', 'info_asset_code', 'fiscTxId', 'txbranch', 'cross_bank',
       'ATM', 'tx_time_cust_id_diff', 'tx_time_cust_id_diff_cust_id_mean',
       'tx_amt_exchg', 'is_foreign', 'tx_amt_exchg_tx_type_mean',
       'tx_amt_exchg_tx_type_max', 'tx_amt_exchg_tx_type_min',
       'tx_amt_exchg_tx_type_std', 'tx_amt_exchg_tx_type_var',
       'tx_amt_exchg_tx_type_median', 'tx_amt_exchg_tx_type_median_diff',
       'tx_amt_exchg_info_asset_code_mean', 'tx_amt_exchg_info_asset_code_max',
       'tx_amt_exchg_info_asset_code_min', 'tx_amt_exchg_info_asset_code_std',
       'tx_amt_exchg_info_asset_code_var',
       'tx_amt_exchg_info_asset_code_median',
       'tx_amt_exchg_info_asset_code_median_diff',
       'tx_amt_exchg_fiscTxId_mean', 'tx_amt_exchg_fiscTxId_max',
       'tx_amt_exchg_fiscTxId_min', 'tx_amt_exchg_fiscTxId_std',
       'tx_amt_exchg_fiscTxId_var', 'tx_amt_exchg_fiscTxId_median',
       'tx_amt_exchg_fiscTxId_median_diff', 'tx_amt_exchg_txbranch_mean',
       'tx_amt_exchg_txbranch_max', 'tx_amt_exchg_txbranch_min',
       'tx_amt_exchg_txbranch_std', 'tx_amt_exchg_txbranch_var',
       'tx_amt_exchg_txbranch_median', 'tx_amt_exchg_txbranch_median_diff'],
      dtype='object')

In [ ]:
remit.columns

Index(['cust_id', 'trans_date', 'trans_no', 'trade_amount_usd',
       'trans_date_cust_id_diff', 'trans_date_cust_id_diff_cust_id_mean',
       'trade_amount_usd_trans_no_mean', 'trade_amount_usd_trans_no_max',
       'trade_amount_usd_trans_no_min', 'trade_amount_usd_trans_no_std',
       'trade_amount_usd_trans_no_var', 'trade_amount_usd_trans_no_median',
       'trade_amount_usd_trans_no_median_diff'],
      dtype='object')

##Preprocessing Part2_transformer

###Config

In [ ]:
class DataSource:
    CCBA = 0
    CDTX = 1
    DP = 2
    REMIT = 3
    CUSTINFO = 4


class FeatureType:
    ID = 0
    DATE = 1
    CATEGORICAL = 2
    NUMERICAL = 3
    TARGET = 4


class CCBAConfig:
    cust_id = FeatureType.ID
    lupay = FeatureType.NUMERICAL
    byymm = FeatureType.DATE
    cycam = FeatureType.NUMERICAL
    usgam = FeatureType.NUMERICAL
    clamt = FeatureType.NUMERICAL
    csamt = FeatureType.NUMERICAL
    inamt = FeatureType.NUMERICAL
    cucsm = FeatureType.NUMERICAL
    cucah = FeatureType.NUMERICAL


class CDTXConfig:
    cust_id = FeatureType.ID
    date = FeatureType.DATE
    country = FeatureType.CATEGORICAL
    amt = FeatureType.NUMERICAL
    cur_type = FeatureType.CATEGORICAL
    #add
    date_cust_id_diff = FeatureType.NUMERICAL
    date_cust_id_diff_cust_id_mean = FeatureType.NUMERICAL
    #
    amt_country_mean = FeatureType.NUMERICAL
    amt_country_max = FeatureType.NUMERICAL
    amt_country_min = FeatureType.NUMERICAL
    amt_country_std = FeatureType.NUMERICAL
    amt_country_var = FeatureType.NUMERICAL
    amt_country_median = FeatureType.NUMERICAL
    amt_country_median_diff = FeatureType.NUMERICAL
    amt_cur_type_mean = FeatureType.NUMERICAL
    amt_cur_type_max = FeatureType.NUMERICAL
    amt_cur_type_min = FeatureType.NUMERICAL
    amt_cur_type_std = FeatureType.NUMERICAL
    amt_cur_type_var = FeatureType.NUMERICAL
    amt_cur_type_median = FeatureType.NUMERICAL
    amt_cur_type_median_diff = FeatureType.NUMERICAL


class DPConfig:
    cust_id = FeatureType.ID
    debit_credit = FeatureType.CATEGORICAL
    tx_date = FeatureType.DATE
    tx_time = FeatureType.CATEGORICAL
    tx_type = FeatureType.CATEGORICAL
    tx_amt = FeatureType.NUMERICAL
    exchg_rate = FeatureType.NUMERICAL
    info_asset_code = FeatureType.CATEGORICAL
    txbranch = FeatureType.CATEGORICAL
    fiscTxId = FeatureType.CATEGORICAL
    cross_bank = FeatureType.CATEGORICAL
    ATM = FeatureType.CATEGORICAL
    #add
    tx_time_cust_id_diff = FeatureType.NUMERICAL
    tx_time_cust_id_diff_cust_id_mean = FeatureType.NUMERICAL
    #
    tx_amt_exchg = FeatureType.NUMERICAL
    is_foreign = FeatureType.CATEGORICAL
    #
    tx_amt_exchg_tx_type_mean = FeatureType.NUMERICAL
    tx_amt_exchg_tx_type_max = FeatureType.NUMERICAL
    tx_amt_exchg_tx_type_min = FeatureType.NUMERICAL
    tx_amt_exchg_tx_type_std = FeatureType.NUMERICAL
    tx_amt_exchg_tx_type_var = FeatureType.NUMERICAL
    tx_amt_exchg_tx_type_median = FeatureType.NUMERICAL
    tx_amt_exchg_tx_type_median_diff = FeatureType.NUMERICAL
    tx_amt_exchg_info_asset_code_mean = FeatureType.NUMERICAL
    tx_amt_exchg_info_asset_code_max = FeatureType.NUMERICAL
    tx_amt_exchg_info_asset_code_min = FeatureType.NUMERICAL
    tx_amt_exchg_info_asset_code_std = FeatureType.NUMERICAL
    tx_amt_exchg_info_asset_code_var = FeatureType.NUMERICAL
    tx_amt_exchg_info_asset_code_median = FeatureType.NUMERICAL
    tx_amt_exchg_info_asset_code_median_diff = FeatureType.NUMERICAL
    tx_amt_exchg_fiscTxId_mean = FeatureType.NUMERICAL
    tx_amt_exchg_fiscTxId_max = FeatureType.NUMERICAL
    tx_amt_exchg_fiscTxId_min = FeatureType.NUMERICAL
    tx_amt_exchg_fiscTxId_std = FeatureType.NUMERICAL
    tx_amt_exchg_fiscTxId_var = FeatureType.NUMERICAL
    tx_amt_exchg_fiscTxId_median = FeatureType.NUMERICAL
    tx_amt_exchg_fiscTxId_median_diff = FeatureType.NUMERICAL
    tx_amt_exchg_txbranch_mean = FeatureType.NUMERICAL
    tx_amt_exchg_txbranch_max = FeatureType.NUMERICAL
    tx_amt_exchg_txbranch_min = FeatureType.NUMERICAL
    tx_amt_exchg_txbranch_std = FeatureType.NUMERICAL
    tx_amt_exchg_txbranch_var = FeatureType.NUMERICAL
    tx_amt_exchg_txbranch_median = FeatureType.NUMERICAL
    tx_amt_exchg_txbranch_median_diff = FeatureType.NUMERICAL


class REMITConfig:
    cust_id = FeatureType.ID
    trans_date = FeatureType.DATE
    trans_no = FeatureType.CATEGORICAL
    trade_amount_usd = FeatureType.NUMERICAL
    #add
    trans_date_cust_id_diff = FeatureType.NUMERICAL
    trans_date_cust_id_diff_cust_id_mean = FeatureType.NUMERICAL
    #
    trade_amount_usd_trans_no_mean = FeatureType.NUMERICAL
    trade_amount_usd_trans_no_max = FeatureType.NUMERICAL
    trade_amount_usd_trans_no_min = FeatureType.NUMERICAL
    trade_amount_usd_trans_no_std = FeatureType.NUMERICAL
    trade_amount_usd_trans_no_var = FeatureType.NUMERICAL
    trade_amount_usd_trans_no_median = FeatureType.NUMERICAL
    trade_amount_usd_trans_no_median_diff = FeatureType.NUMERICAL


class CUSTINFOConfig:
    cust_id = FeatureType.ID
    alert_key = FeatureType.ID
    risk_rank = FeatureType.CATEGORICAL
    occupation_code = FeatureType.CATEGORICAL
    total_asset = FeatureType.NUMERICAL
    AGE = FeatureType.CATEGORICAL
    date = FeatureType.DATE
    sar_flag = FeatureType.CATEGORICAL


CONFIG_MAP = {
    DataSource.CCBA: CCBAConfig,
    DataSource.CDTX: CDTXConfig,
    DataSource.DP: DPConfig,
    DataSource.REMIT: REMITConfig,
    DataSource.CUSTINFO: CUSTINFOConfig,
}

DATA_SOURCES = [DataSource.CCBA, DataSource.CDTX, DataSource.DP, DataSource.REMIT, DataSource.CUSTINFO]

###Utils

In [ ]:
import yaml
import json
import itertools
import pickle
import inspect
from functools import lru_cache

def save_pickle(dic, save_path):
    with open(save_path, 'wb') as f:
        pickle.dump(dic, f, protocol=4)


def load_pickle(load_path):
    with open(load_path, 'rb') as f:
        message_dict = pickle.load(f)
    return message_dict


def load_yaml(fp):
    return yaml.load(open(fp, "r", encoding='utf-8'),
                     Loader=yaml.SafeLoader)


def save_yaml(data, fp):
    yaml.dump(
        data,
        open(fp, "w", encoding="utf-8"),
        allow_unicode=True,
        default_flow_style=False)


def save_json(data, fp):
    with open(fp, "w", encoding="utf-8") as f:
        json_str = json.dumps(data, ensure_ascii=False, indent=4)
        f.write("{}\n".format(json_str))
        f.flush()


def load_json(fp):
    with open(fp, 'r', encoding='utf-8') as f:
        return json.loads(f.read())


@lru_cache(None)
def get_feats_name(config):
    input_feats = []
    for name, _type in inspect.getmembers(config):
        if inspect.ismethod(_type) or name.startswith('_'):
            continue
        if getattr(config, name) in [FeatureType.NUMERICAL, FeatureType.CATEGORICAL]:
            input_feats.append(name)
    return input_feats

### Map Date and target to `custinfo`

原作法為alert key為主，所有資料去對alert key，現在改以customerinfo為主，所有資料去對customerid

In [ ]:
date = pd.concat([pdate, tdate], axis=0)
cinfo = cinfo.merge(date, on='alert_key', how='left')
cinfo = cinfo.merge(answer, on='alert_key', how='left')
cinfo

,alert_key,cust_id,risk_rank,occupation_code,total_asset,AGE,date,sar_flag
0,352249,82595ac69158ae08d34156784bdec0d9e2ca5b242b6d2a...,1,19,1465816.0,7,365,NaN
1,352253,b212d14cb35676926682b2cf849e295d948888f556c07e...,1,2,98177.0,2,365,NaN
2,352254,e5b0002791c7852644a2730abeaa893cdf14a072ef7812...,1,19,2052922.0,7,365,NaN
3,352280,74214c478dc6519fbefe4bc31693865bdcd698ab974b64...,3,15,201906.0,5,365,NaN
4,352282,0340e7611f0d82c3cb87e6194fa14bb2ccf8afbf1b3418...,1,12,7450.0,5,365,NaN
...,...,...,...,...,...,...,...,...
25746,352123,b600c0720096c241f5aec16b096c6a353492eee8a5855a...,1,17,12207.0,2,364,0.0
25747,352124,06c5ea5ccda4dfd8839c0dec8646fb3071d2c02883ef8a...,1,17,259985.0,4,364,0.0
25748,352125,0c2dc5fedc3689abf5ff4be14fe8fea8d23d22068297c2...,3,19,928963.0,3,364,0.0
25749,352128,ffe5f2bd86ecfd7d0a0f4c4b76dd5c312649be95eb8b42...,3,19,21647.0,4,364,0.0
25750,352132,c49b33d1fde790ec03584672903f296e486615adfdc989...,1,19,3218731.0,3,364,0.0

### Process Numerical and Categorical

In [ ]:
#QuantileTransformer
def normalize(col):
    qt = QuantileTransformer(
        n_quantiles=10_000, 
        random_state=0, 
        subsample=min(5*10**5, len(col)),
        output_distribution='normal'
    )
    return qt.fit_transform(col)

def process_numerical(col):
    col = normalize(col)
    col = np.nan_to_num(col, nan=0)
    return col

def process_catgorical(col):
    col.fillna('NULL', inplace=True)
    map_dict = {v:i for i, v in enumerate(set(col.unique()))}
    col = col.map(map_dict)
    return col

In [ ]:
datas = [
    (ccba, DataSource.CCBA), 
    (cdtx, DataSource.CDTX),
    (dp, DataSource.DP),
    (remit, DataSource.REMIT),
    (cinfo, DataSource.CUSTINFO),
]

num_cat_dict = {}

# process numerical and categorical and data_source
for data, data_source in datas:
    print('ok')
    config = CONFIG_MAP[data_source]
    cols = data.columns
    numericals = []
    for col in cols:
        feature_type = getattr(config, col)
        if feature_type == FeatureType.NUMERICAL and col != 'sar_flag':
            numericals.append(col)
        elif feature_type == FeatureType.CATEGORICAL and col != 'sar_flag':
            data[col] = process_catgorical(data[col].copy())
            num_cat = data[col].nunique()
            if data_source not in num_cat_dict:
                num_cat_dict[data_source] = {}
            num_cat_dict[data_source][col] = num_cat

    if numericals:
        data[numericals] = process_numerical(data[numericals].copy())
    data['data_source'] = data_source

ok
ok
ok
ok
ok

In [ ]:
save_yaml(num_cat_dict, 'num_cat_dict.yml')

In [ ]:
datas = [d[0] for d in datas]

In [ ]:
datas_g = [d.groupby(by='cust_id') for d in datas]

In [ ]:
def get_date(d):
    ds = d.data_source
    
    if ds == DataSource.CCBA:
        date = d.byymm
    elif ds == DataSource.CDTX:
        date = d.date
    elif ds == DataSource.DP:
        date = d.tx_date
    elif ds == DataSource.REMIT:
        date = d.trans_date
    elif ds == DataSource.CUSTINFO:
        date = d.date
    return date, ds


cust_ids = cinfo.cust_id.unique()
save_data = edict()
for cust_id in tqdm(cust_ids):
    # get all data from each group
    cust_data = []
    for d in datas_g:
        if not cust_id in d.groups:
            continue
        cust_data += d.get_group(cust_id).to_dict('records')
    for i in range(len(cust_data)):
        cust_data[i] = edict(cust_data[i])
    
    # sort by date
    cust_data.sort(key=get_date)
    
    # generate source list and target_mask
    source_list = []
    train_mask = []
    test_mask = []
    for i, c in enumerate(cust_data):
        ds = c.data_source
        source_list.append(ds)
        if ds != DataSource.CUSTINFO:
            pass
        elif np.isnan(c.sar_flag):
            test_mask.append(i)
        else:
            train_mask.append(i)
    
    # save data
    save_data[cust_id] = edict({
        'sources': source_list,
        'train_mask': train_mask,
        'test_mask': test_mask,
        'cust_data': cust_data,
    })

100%|██████████| 7708/7708 [03:22<00:00, 38.04it/s]

### check num of train_mask, test_mask is correct

In [ ]:
isna = cinfo.sar_flag.isna()
train_num = sum(~isna)
test_num = sum(isna)

train_num2 = 0
test_num2 = 0
for v in save_data.values():
    train_num2 += len(v.train_mask)
    test_num2 += len(v.test_mask)


print(train_num == train_num2)
print(test_num == test_num2)

True
True

In [ ]:
save_pickle(save_data, 'cust_data.pkl')

In [ ]:
from google.colab import files
files.download('cust_data.pkl')

### length distribution

### check target_mask distribution

In [ ]:
# train_mask = []
# test_mask = []
# for v in save_data.values():
#     train_mask += v.train_mask
#     test_mask += v.test_mask

# display(pd.DataFrame(data=train_mask, columns=['train']).describe(percentiles=np.linspace(0,1,11)))
# display(pd.DataFrame(data=test_mask, columns=['test']).describe(percentiles=np.linspace(0,1,11)))

               train
count   25751.000000
mean      803.571978
std      4353.261784
min         0.000000
0%          0.000000
10%         8.000000
20%        33.000000
30%        75.000000
40%       130.000000
50%       208.000000
60%       313.000000
70%       471.000000
80%       717.000000
90%      1209.000000
100%   131825.000000
max    131825.000000

       test
count     0
unique    0
top     NaN
freq    NaN

In [ ]:
# data = load_pickle('./data/cust_data.pkl')
# len(data)

7708

In [ ]:
# sars = set()
# for cust_id, v in data.items():
#     for idx in v.train_mask:
#         if v.cust_data[idx].sar_flag == 1:
#             sars.add(cust_id)
#             break
# len(sars)

233

In [ ]:
# num1 = []
# for cust_id in sars:
#     d = data[cust_id]
#     tmp = 0
#     for idx in d.train_mask:
#         tmp += (d.cust_data[idx].sar_flag == 1)
#     num1.append(tmp)
# sum(num1)

234

In [ ]:
# # num_sar = []
# num_len = []
# num0 = []
# num1 = []
# for k, d in data.items():
#     tmp0 = 0
#     tmp1 = 0
#     for idx in d.train_mask:
#         tmp0 += d.cust_data[idx].sar_flag == 0
#         tmp1 += d.cust_data[idx].sar_flag == 1
#     num0.append(tmp0)
#     num1.append(tmp1)
#     num_len.append(len(d.cust_data))

In [ ]:
# df = pd.DataFrame({'num0': num0, 'num1':num1,'num_len': num_len})

In [ ]:
# df.describe()

              num0         num1        num_len
count  7708.000000  7708.000000    7708.000000
mean      3.071095     0.030358     404.102880
std       9.311131     0.172336    2518.273585
min       0.000000     0.000000       1.000000
25%       1.000000     0.000000      29.000000
50%       1.000000     0.000000     138.000000
75%       2.000000     0.000000     399.000000
max     236.000000     2.000000  135334.000000

In [ ]:
# df[df.num1>0].describe()

             num0        num1        num_len
count  233.000000  233.000000     233.000000
mean     2.802575    1.004292    1887.922747
std      8.547262    0.065512    8882.960612
min      0.000000    1.000000      21.000000
25%      0.000000    1.000000     295.000000
50%      0.000000    1.000000     641.000000
75%      0.000000    1.000000    1272.000000
max     72.000000    2.000000  124139.000000

In [ ]:
# # df1 = df[df.num1>0]
# df[df.num_len == df.num_len.max()]

     num0  num1  num_len
136    68     0   135334

In [ ]:
# df[df.num1==0].describe()

              num0    num1        num_len
count  7475.000000  7475.0    7475.000000
mean      3.079465     0.0     357.851371
std       9.334339     0.0    2004.813683
min       0.000000     0.0       1.000000
25%       1.000000     0.0      27.000000
50%       1.000000     0.0     130.000000
75%       2.000000     0.0     380.000000
max     236.000000     0.0  135334.000000

In [ ]:
# mask_ids = []
# for k, v in data.items():
#     for i, idx in enumerate(v.train_mask):
#         if i == 0:
#             mask_ids.append(idx)
#         else:
#             mask_ids.append(idx-v.train_mask[i-1])
# pd.DataFrame({'mask_ids': mask_ids}).describe(percentiles=np.arange(.9, 1.01, 0.01))

           mask_ids
count  23906.000000
mean      68.353049
std      486.181119
min        0.000000
50%       10.000000
90%      137.000000
91%      158.000000
92%      178.000000
93%      204.000000
94%      238.000000
95%      282.750000
96%      343.000000
97%      426.850000
98%      553.900000
99%      830.950000
100%   42132.000000
max    42132.000000

In [ ]:
# # get len of cust_data of save_data
# lens = []
# for k, v in save_data.items():
#     lens.append(len(v.sources))
# pd.DataFrame(data=lens, columns=None).describe(percentiles=[.25, .5, .75, .9, .95, .99])

                   0
count    7708.000000
mean      404.102880
std      2518.273585
min         1.000000
25%        29.000000
50%       138.000000
75%       399.000000
90%       848.900000
95%      1243.650000
99%      2747.650000
max    135334.000000

#Preprocessing Part3_XGboost

## Import Packages

In [ ]:
pip install --upgrade category_encoders

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting category_encoders
  Downloading category_encoders-2.5.1.post0-py2.py3-none-any.whl (72 kB)
     |████████████████████████████████| 72 kB 825 kB/s
Requirement already satisfied: pandas>=1.0.5 in /usr/local/lib/python3.8/dist-packages (from category_encoders) (1.3.5)
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.8/dist-packages (from category_encoders) (1.21.6)
Requirement already satisfied: scikit-learn>=0.20.0 in /usr/local/lib/python3.8/dist-packages (from category_encoders) (1.0.2)
Requirement already satisfied: statsmodels>=0.9.0 in /usr/local/lib/python3.8/dist-packages (from category_encoders) (0.12.2)
Requirement already satisfied: patsy>=0.5.1 in /usr/local/lib/python3.8/dist-packages (from category_encoders) (0.5.3)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.8/dist-packages (from category_encoders) (1.7.3)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=1.0.5->category_encoders) (2022.6)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=1.0.5->category_encoders) (2.8.2)
Requirement already satisfied: six in /usr/local/lib/python3.8/dist-packages (from patsy>=0.5.1->category_encoders) (1.15.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.8/dist-packages (from scikit-learn>=0.20.0->category_encoders) (3.1.0)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.8/dist-packages (from scikit-learn>=0.20.0->category_encoders) (1.2.0)
Installing collected packages: category-encoders
Successfully installed category-encoders-2.5.1.post0

In [ ]:
# basic stuffs
import csv
import time
import sys
import os
import math
import random as rand
from typing import Dict
import collections

# other library
import numpy as np
import pandas as pd

# visualization tools
import tqdm
import matplotlib.pyplot as plt

#Preprocessing
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder
import category_encoders as ce

# PyTorch library
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torch.utils import data 
from torch.utils.data import Dataset, DataLoader

## Fix Randomization Seed

In [ ]:
SEED = 5566 # Do not modify
use_gpu = torch.cuda.is_available()
device = torch.device("cuda" if use_gpu else "cpu")

torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False
torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)
rand.seed(SEED)
np.random.seed(SEED)

##Parameters

In [ ]:
TIME_FRAME_SIZE = 5
DAY_FRAME_SIZE = 7

#setting
pd.set_option('precision', 4)
pd.set_option("display.max_columns",1000)

## Combining files + 前n筆交易

In [ ]:
# #轉小時制
# def da_to_hr(day,hour):
#     return int(day*24+hour)

# def count_trans_diff(date, df):
#     tmp = []
#     #有時間的_dp
#     if len(df.columns)>1:
#         if df.shape[0] < TIME_FRAME_SIZE:
#             for i in range(df.shape[0]):
#                 if i==0:
#                       tmp.append(da_to_hr(date,24)-da_to_hr(df.iloc[i,0],df.iloc[i,1]))
#                 else:
#                       tmp.append(da_to_hr(df.iloc[i-1,0],df.iloc[i-1,1])-da_to_hr(df.iloc[i,0],df.iloc[i,1]))
#             for k in range(TIME_FRAME_SIZE-df.shape[0]):
#                 tmp.append(np.nan)         
#         else:
#             for i in range(TIME_FRAME_SIZE):
#                 if i==0:
#                       tmp.append(da_to_hr(date,24)-da_to_hr(df.iloc[i,0],df.iloc[i,1]))
#                 else:
#                       tmp.append(da_to_hr(df.iloc[i-1,0],df.iloc[i-1,1])-da_to_hr(df.iloc[i,0],df.iloc[i,1]))
#     else:
#         if df.shape[0] < TIME_FRAME_SIZE:
#             for i in range(df.shape[0]):
#                 if i==0:
#                       tmp.append(date-int(df.iloc[i]))
#                 else:
#                       tmp.append(int(df.iloc[i-1])-int(df.iloc[i]))
#             for k in range(TIME_FRAME_SIZE-df.shape[0]):
#                 tmp.append(np.nan)      
#         else:
#             for i in range(TIME_FRAME_SIZE):
#                 if i==0:
#                       tmp.append(date-int(df.iloc[i]))
#                 else:
#                       tmp.append(int(df.iloc[i-1])-int(df.iloc[i]))
#     tmp.append(sum(tmp)/df.shape[0])
#     return tmp

In [ ]:
dp = dp.drop(columns=['tx_amt','exchg_rate'])

In [ ]:
len(dp.columns)

42

In [ ]:
def preprocess():
    cus_data = [ccba, cdtx, dp, remit]
    date_col = ['byymm', 'date', 'tx_date', 'trans_date']
    #ccba(-byymm), cdtx(-date), dp(-tx_date, -tx_time, -exchg_rate), trans_date(-trans_date)
    data_use_col = [[1,3,4,5,6,7,8,9],[i for i in range(2,21)],[1]+[i for i in range(4,42)],[i for i in range(2,13)]]

    # do label encoding_CR/DB->0/1
    le = LabelEncoder()
    dp.debit_credit = le.fit_transform(dp.debit_credit)
    dp.is_foreign = le.fit_transform(dp.is_foreign)

    cnts = [0] * 4
    cnts_2 = [0] * 4
    labels = []
    training_data = []

    print('Combining...')
    start = time.time()
    for i in range(answer.shape[0]):
        # from alert key to get customer information
        cur_data = answer.iloc[i]
        alert_key, label = cur_data['alert_key'], cur_data['sar_flag']
        cus_info = cinfo[cinfo['alert_key']==alert_key].iloc[0]
        cus_id = cus_info['cust_id']
        cus_features = cus_info.values[2:]

        date = pdate[pdate['alert_key']==alert_key].iloc[0]['date']


        #print('Combining ccba, cdtx, dp, remit1...')
        cnt = 0
        for j, df in enumerate(cus_data):
            cus_additional_info = df[df['cust_id'] == cus_id]
            cus_additional_info = cus_additional_info[cus_additional_info[date_col[j]]<=date]

            ##ccba(取前一個月)
            if j == 0:
                if cus_additional_info.empty:
                    cnts[j] += 1
                    len_item = len(data_use_col[j])
                    cus_features = np.concatenate((cus_features, [np.nan] * len_item), axis=0)

                else:
                    cur_cus_feature = cus_additional_info.loc[cus_additional_info[date_col[j]].idxmax()]               
                    cur_cus_feature = cur_cus_feature.values[data_use_col[j]]
                    cus_features = np.concatenate((cus_features, cur_cus_feature), axis=0)  
            
            ##cdtx, dp, remit1(取前TIME_FRAME_SIZE筆交易)
            else:
                if cus_additional_info.empty:
                    cnts[j] += 1
                    len_item = len(data_use_col[j])
                    cus_features = np.concatenate((cus_features, [np.nan] * len_item * TIME_FRAME_SIZE), axis=0)
                    #new feature_trans_num
                    cus_features = np.concatenate((cus_features, [0]), axis=0) 
                else:
                    trans_diff = []
                    if j == 2:
                        cus_additional_info = cus_additional_info.sort_values(by=[date_col[j],'tx_time'], ascending=False)
                        #print(cus_additional_info)
                        
                    else:
                        cus_additional_info = cus_additional_info.sort_values(by=date_col[j], ascending=False)                   
                        #print(cus_additional_info[date_col[j]])
                        
                    #print(date)
                    if cus_additional_info.shape[0] < TIME_FRAME_SIZE:
                        cur_cus_feature = cus_additional_info.iloc[:, data_use_col[j]].values.reshape(-1)
                        miss_n = TIME_FRAME_SIZE - cus_additional_info.shape[0]
                        #count missing time frame
                        cnts_2[j] += miss_n
                        len_item = len(data_use_col[j])* miss_n
                        cur_cus_feature = np.concatenate((cur_cus_feature, [np.nan] * len_item), axis=0)

                        #new_feature2
                        trans_num = cus_additional_info.shape[0]

                    else:
                        cur_cus_feature = cus_additional_info.iloc[0:TIME_FRAME_SIZE, data_use_col[j]].values.reshape(-1)
                        #new_feature2
                        trans_num = TIME_FRAME_SIZE                
                    
                    
                    #print(cur_cus_feature)


                    cus_features = np.concatenate((cus_features, cur_cus_feature), axis=0)
                    #add new feature_trans_num
                    cus_features = np.concatenate((cus_features, [trans_num]), axis=0)
        #add_cus_id
        cus_features = np.concatenate((cus_features, [cus_id]), axis=0)


        labels.append(label)
        training_data.append(cus_features)
        print('\r processing data {}/{}'.format(i+1, answer.shape[0]), end = '')


        #for testing
        # if (i==100):
        #     break
    print('Processing time: {:.3f} secs'.format(time.time()-start))
    print('Missing value of 4 csvs:', cnts)
    print('Missing time frames of 4 csvs:', cnts_2)


    print('Start processing testing data')
    testing_data, testing_alert_key = [], []
    for i in range(tdate.shape[0]):
        # from alert key to get customer information
        cur_data = tdate.iloc[i]
        alert_key, date = cur_data['alert_key'], cur_data['date']

        cus_info = cinfo[cinfo['alert_key']==alert_key].iloc[0]
        cus_id = cus_info['cust_id']
        cus_features = cus_info.values[2:]



        #print('Combining ccba, cdtx, dp, remit1...')
        cnt = 0
        for j, df in enumerate(cus_data):
            cus_additional_info = df[df['cust_id'] == cus_id]
            cus_additional_info = cus_additional_info[cus_additional_info[date_col[j]]<=date]

            ##ccba(取前一個月)
            if j == 0:
                if cus_additional_info.empty:
                    len_item = len(data_use_col[j])
                    cus_features = np.concatenate((cus_features, [np.nan] * len_item), axis=0)

                else:
                    cur_cus_feature = cus_additional_info.loc[cus_additional_info[date_col[j]].idxmax()]               
                    cur_cus_feature = cur_cus_feature.values[data_use_col[j]]
                    cus_features = np.concatenate((cus_features, cur_cus_feature), axis=0)  

            ##cdtx, dp, remit1(取前TIME_FRAME_SIZE筆交易)
            else:              
                if cus_additional_info.empty:
                    len_item = len(data_use_col[j])
                    cus_features = np.concatenate((cus_features, [np.nan] * len_item * TIME_FRAME_SIZE), axis=0)
                    #new feature_trans_num
                    cus_features = np.concatenate((cus_features, [0]), axis=0)                    
                else:
                    if j == 2:
                        cus_additional_info = cus_additional_info.sort_values(by=[date_col[j],'tx_time'], ascending=False)
                    else:
                        cus_additional_info = cus_additional_info.sort_values(by=date_col[j], ascending=False)



                    #print(cus_additional_info)
                    if cus_additional_info.shape[0] < TIME_FRAME_SIZE:
                        cur_cus_feature = cus_additional_info.iloc[:, data_use_col[j]].values.reshape(-1)
                        miss_n = TIME_FRAME_SIZE - cus_additional_info.shape[0]
                        len_item = len(data_use_col[j])* miss_n
                        cur_cus_feature = np.concatenate((cur_cus_feature, [np.nan] * len_item), axis=0)
                        #new_feature2
                        trans_num = cus_additional_info.shape[0]
                    else:
                        cur_cus_feature = cus_additional_info.iloc[0:TIME_FRAME_SIZE, data_use_col[j]].values.reshape(-1)
                        #new_feature2
                        trans_num = TIME_FRAME_SIZE
                    #print(cur_cus_feature)

                    cus_features = np.concatenate((cus_features, cur_cus_feature), axis=0)
                    #add new feature_trans_num
                    cus_features = np.concatenate((cus_features, [trans_num]), axis=0) 
        #add cus id
        cus_features = np.concatenate((cus_features, [cus_id]), axis=0)

        testing_data.append(cus_features)
        testing_alert_key.append(alert_key)
        # print(cus_features)
        print('\r processing data {}/{}'.format(i+1, tdate.shape[0]), end = '')
        #for testing
        # if (i==100):
        #     break
    return training_data, labels, testing_data, testing_alert_key

In [ ]:
# data preprocessing(training_data~1hr40min)
training_data, labels, testing_data, testing_alert_key = preprocess()
print(training_data[0])
print(len(training_data))
print(len(testing_data))

Combining...

IndexError: ignored

In [ ]:
#存成dataframe
COL_NAME = ['risk_rank', 'occupation_code', 'total_asset', 'AGE', 'lupay', 'cycam', 'usgam', 'clamt', 'csamt', 'inamt', 'cucsm', 'cucah']
tmp_col_name = [['country', 'cur_type', 'amt', 'date_cust_id_diff', \
       'date_cust_id_diff_cust_id_mean', 'amt_country_mean', 'amt_country_max', \
       'amt_country_min', 'amt_country_std', 'amt_country_var', \
       'amt_country_median', 'amt_country_median_diff', 'amt_cur_type_mean', \
       'amt_cur_type_max', 'amt_cur_type_min', 'amt_cur_type_std', \
       'amt_cur_type_var', 'amt_cur_type_median', 'amt_cur_type_median_diff'], \
       ['debit_credit','tx_type', \
       'info_asset_code', 'fiscTxId', 'txbranch', 'cross_bank', 'ATM', \
       'tx_time_cust_id_diff', 'tx_time_cust_id_diff_cust_id_mean', \
       'tx_amt_exchg', 'is_foreign', 'tx_amt_exchg_tx_type_mean', \
       'tx_amt_exchg_tx_type_max', 'tx_amt_exchg_tx_type_min', \
       'tx_amt_exchg_tx_type_std', 'tx_amt_exchg_tx_type_var', \
       'tx_amt_exchg_tx_type_median', 'tx_amt_exchg_tx_type_median_diff', \
       'tx_amt_exchg_info_asset_code_mean', 'tx_amt_exchg_info_asset_code_max', \
       'tx_amt_exchg_info_asset_code_min', 'tx_amt_exchg_info_asset_code_std', \
       'tx_amt_exchg_info_asset_code_var', \
       'tx_amt_exchg_info_asset_code_median', \
       'tx_amt_exchg_info_asset_code_median_diff', \
       'tx_amt_exchg_fiscTxId_mean', 'tx_amt_exchg_fiscTxId_max', \
       'tx_amt_exchg_fiscTxId_min', 'tx_amt_exchg_fiscTxId_std', \
       'tx_amt_exchg_fiscTxId_var', 'tx_amt_exchg_fiscTxId_median', \
       'tx_amt_exchg_fiscTxId_median_diff', 'tx_amt_exchg_txbranch_mean', \
       'tx_amt_exchg_txbranch_max', 'tx_amt_exchg_txbranch_min', \
       'tx_amt_exchg_txbranch_std', 'tx_amt_exchg_txbranch_var', \
       'tx_amt_exchg_txbranch_median', 'tx_amt_exchg_txbranch_median_diff'], \
       ['trans_no', 'trade_amount_usd', \
       'trans_date_cust_id_diff', 'trans_date_cust_id_diff_cust_id_mean', \
       'trade_amount_usd_trans_no_mean', 'trade_amount_usd_trans_no_max', \
       'trade_amount_usd_trans_no_min', 'trade_amount_usd_trans_no_std', \
       'trade_amount_usd_trans_no_var', 'trade_amount_usd_trans_no_median', \
       'trade_amount_usd_trans_no_median_diff']]
for group,i in enumerate(tmp_col_name):
    for j in range (1, TIME_FRAME_SIZE+1):
        for k in i:
            COL_NAME.append(f'{k}_{j}')
    #New feature columns
    if group == 0:
        COL_NAME.append('cdtx_trans_num')
    elif group == 1:
        COL_NAME.append('dp_trans_num')
    if group == 2:
        COL_NAME.append('remit_trans_num')

#add cus id
COL_NAME.append('cust_id')

df = pd.DataFrame(data=training_data, columns=COL_NAME)
df_ans = pd.DataFrame(data=labels, columns=['labels'])
df2 = pd.DataFrame(data=testing_data, columns=COL_NAME)
df2_alert_key = pd.DataFrame(data=testing_alert_key, columns=['alert_key'])
df.head(50)

In [ ]:
#drop重複欄位
#date_cust_id_diff_cust_id_mean,tx_time_cust_id_diff_cust_id_mean,trans_date_cust_id_diff_cust_id_mean(2-5)
tmp_drop_columns = ['date_cust_id_diff_cust_id_mean','tx_time_cust_id_diff_cust_id_mean','trans_date_cust_id_diff_cust_id_mean']
drop_columns = []
for i in range (2, TIME_FRAME_SIZE+1):
    for j in tmp_drop_columns:
        drop_columns.append(f'{j}_{i}')
print(drop_columns)

df = df.drop(columns=drop_columns)
df2 = df2.drop(columns=drop_columns)

In [ ]:
for i in drop_columns:
    COL_NAME.remove(i)
print(COL_NAME)

In [ ]:
df.head()

In [ ]:
#下載
from google.colab import files

df.to_csv('training_data_xgboost.csv') 
files.download('training_data_xgboost.csv')
df_ans.to_csv('training_data_labels_xgboost.csv') 
files.download('training_data_labels_xgboost.csv')

df2.to_csv('testing_data_xgboost.csv') 
files.download('testing_data_xgboost.csv')
df2_alert_key.to_csv('testing_alert_key_xgboost.csv') 
files.download('testing_alert_key_xgboost.csv')

In [ ]:
df.describe()

## Missing Values

In [ ]:
#Simple adding Missing Value


#數值與非數值欄位區分
numerical_column = ['total_asset','lupay', 'cycam', 'usgam', 'clamt', 'csamt', 'inamt', 'cucsm', 'cucah','date_cust_id_diff_cust_id_mean_1','tx_time_cust_id_diff_cust_id_mean_1','trans_date_cust_id_diff_cust_id_mean_1','cdtx_trans_num','dp_trans_num','remit_trans_num']
non_numerical_column = ['risk_rank', 'occupation_code', 'AGE']

tmp_numerical_col_name = ['amt', 'date_cust_id_diff', 'amt_country_mean', 'amt_country_max', \
       'amt_country_min', 'amt_country_std', 'amt_country_var', \
       'amt_country_median', 'amt_country_median_diff', 'amt_cur_type_mean', \
       'amt_cur_type_max', 'amt_cur_type_min', 'amt_cur_type_std', \
       'amt_cur_type_var', 'amt_cur_type_median', 'amt_cur_type_median_diff', \
       'tx_time_cust_id_diff', 'tx_amt_exchg', 'tx_amt_exchg_tx_type_mean', \
       'tx_amt_exchg_tx_type_max', 'tx_amt_exchg_tx_type_min', \
       'tx_amt_exchg_tx_type_std', 'tx_amt_exchg_tx_type_var', \
       'tx_amt_exchg_tx_type_median', 'tx_amt_exchg_tx_type_median_diff', \
       'tx_amt_exchg_info_asset_code_mean', 'tx_amt_exchg_info_asset_code_max', \
       'tx_amt_exchg_info_asset_code_min', 'tx_amt_exchg_info_asset_code_std', \
       'tx_amt_exchg_info_asset_code_var', \
       'tx_amt_exchg_info_asset_code_median', \
       'tx_amt_exchg_info_asset_code_median_diff', \
       'tx_amt_exchg_fiscTxId_mean', 'tx_amt_exchg_fiscTxId_max', \
       'tx_amt_exchg_fiscTxId_min', 'tx_amt_exchg_fiscTxId_std', \
       'tx_amt_exchg_fiscTxId_var', 'tx_amt_exchg_fiscTxId_median', \
       'tx_amt_exchg_fiscTxId_median_diff', 'tx_amt_exchg_txbranch_mean', \
       'tx_amt_exchg_txbranch_max', 'tx_amt_exchg_txbranch_min', \
       'tx_amt_exchg_txbranch_std', 'tx_amt_exchg_txbranch_var', \
       'tx_amt_exchg_txbranch_median', 'tx_amt_exchg_txbranch_median_diff', \
       'trade_amount_usd', 'trans_date_cust_id_diff', \
       'trade_amount_usd_trans_no_mean', 'trade_amount_usd_trans_no_max', \
       'trade_amount_usd_trans_no_min', 'trade_amount_usd_trans_no_std', \
       'trade_amount_usd_trans_no_var', 'trade_amount_usd_trans_no_median', \
       'trade_amount_usd_trans_no_median_diff']
tmp_non_numerical_col_name = ['country', 'cur_type', 'debit_credit', 'tx_type', 'info_asset_code', 'fiscTxId', 'txbranch', 'cross_bank', 'ATM','is_foreign', 'trans_no']
for i in range (1, TIME_FRAME_SIZE+1):
    for j in tmp_numerical_col_name:
        numerical_column.append(f'{j}_{i}')
    for j in tmp_non_numerical_col_name:
        non_numerical_column.append(f'{j}_{i}')

print(numerical_column)
print(non_numerical_column)

['total_asset', 'lupay', 'cycam', 'usgam', 'clamt', 'csamt', 'inamt', 'cucsm', 'cucah', 'date_cust_id_diff_cust_id_mean_1', 'tx_time_cust_id_diff_cust_id_mean_1', 'trans_date_cust_id_diff_cust_id_mean_1', 'cdtx_trans_num', 'dp_trans_num', 'remit_trans_num', 'amt_1', 'date_cust_id_diff_1', 'amt_country_mean_1', 'amt_country_max_1', 'amt_country_min_1', 'amt_country_std_1', 'amt_country_var_1', 'amt_country_median_1', 'amt_country_median_diff_1', 'amt_cur_type_mean_1', 'amt_cur_type_max_1', 'amt_cur_type_min_1', 'amt_cur_type_std_1', 'amt_cur_type_var_1', 'amt_cur_type_median_1', 'amt_cur_type_median_diff_1', 'tx_time_cust_id_diff_1', 'tx_amt_exchg_1', 'tx_amt_exchg_tx_type_mean_1', 'tx_amt_exchg_tx_type_max_1', 'tx_amt_exchg_tx_type_min_1', 'tx_amt_exchg_tx_type_std_1', 'tx_amt_exchg_tx_type_var_1', 'tx_amt_exchg_tx_type_median_1', 'tx_amt_exchg_tx_type_median_diff_1', 'tx_amt_exchg_info_asset_code_mean_1', 'tx_amt_exchg_info_asset_code_max_1', 'tx_amt_exchg_info_asset_code_min_1', 'tx_amt_exchg_info_asset_code_std_1', 'tx_amt_exchg_info_asset_code_var_1', 'tx_amt_exchg_info_asset_code_median_1', 'tx_amt_exchg_info_asset_code_median_diff_1', 'tx_amt_exchg_fiscTxId_mean_1', 'tx_amt_exchg_fiscTxId_max_1', 'tx_amt_exchg_fiscTxId_min_1', 'tx_amt_exchg_fiscTxId_std_1', 'tx_amt_exchg_fiscTxId_var_1', 'tx_amt_exchg_fiscTxId_median_1', 'tx_amt_exchg_fiscTxId_median_diff_1', 'tx_amt_exchg_txbranch_mean_1', 'tx_amt_exchg_txbranch_max_1', 'tx_amt_exchg_txbranch_min_1', 'tx_amt_exchg_txbranch_std_1', 'tx_amt_exchg_txbranch_var_1', 'tx_amt_exchg_txbranch_median_1', 'tx_amt_exchg_txbranch_median_diff_1', 'trade_amount_usd_1', 'trans_date_cust_id_diff_1', 'trade_amount_usd_trans_no_mean_1', 'trade_amount_usd_trans_no_max_1', 'trade_amount_usd_trans_no_min_1', 'trade_amount_usd_trans_no_std_1', 'trade_amount_usd_trans_no_var_1', 'trade_amount_usd_trans_no_median_1', 'trade_amount_usd_trans_no_median_diff_1', 'amt_2', 'date_cust_id_diff_2', 'amt_country_mean_2', 'amt_country_max_2', 'amt_country_min_2', 'amt_country_std_2', 'amt_country_var_2', 'amt_country_median_2', 'amt_country_median_diff_2', 'amt_cur_type_mean_2', 'amt_cur_type_max_2', 'amt_cur_type_min_2', 'amt_cur_type_std_2', 'amt_cur_type_var_2', 'amt_cur_type_median_2', 'amt_cur_type_median_diff_2', 'tx_time_cust_id_diff_2', 'tx_amt_exchg_2', 'tx_amt_exchg_tx_type_mean_2', 'tx_amt_exchg_tx_type_max_2', 'tx_amt_exchg_tx_type_min_2', 'tx_amt_exchg_tx_type_std_2', 'tx_amt_exchg_tx_type_var_2', 'tx_amt_exchg_tx_type_median_2', 'tx_amt_exchg_tx_type_median_diff_2', 'tx_amt_exchg_info_asset_code_mean_2', 'tx_amt_exchg_info_asset_code_max_2', 'tx_amt_exchg_info_asset_code_min_2', 'tx_amt_exchg_info_asset_code_std_2', 'tx_amt_exchg_info_asset_code_var_2', 'tx_amt_exchg_info_asset_code_median_2', 'tx_amt_exchg_info_asset_code_median_diff_2', 'tx_amt_exchg_fiscTxId_mean_2', 'tx_amt_exchg_fiscTxId_max_2', 'tx_amt_exchg_fiscTxId_min_2', 'tx_amt_exchg_fiscTxId_std_2', 'tx_amt_exchg_fiscTxId_var_2', 'tx_amt_exchg_fiscTxId_median_2', 'tx_amt_exchg_fiscTxId_median_diff_2', 'tx_amt_exchg_txbranch_mean_2', 'tx_amt_exchg_txbranch_max_2', 'tx_amt_exchg_txbranch_min_2', 'tx_amt_exchg_txbranch_std_2', 'tx_amt_exchg_txbranch_var_2', 'tx_amt_exchg_txbranch_median_2', 'tx_amt_exchg_txbranch_median_diff_2', 'trade_amount_usd_2', 'trans_date_cust_id_diff_2', 'trade_amount_usd_trans_no_mean_2', 'trade_amount_usd_trans_no_max_2', 'trade_amount_usd_trans_no_min_2', 'trade_amount_usd_trans_no_std_2', 'trade_amount_usd_trans_no_var_2', 'trade_amount_usd_trans_no_median_2', 'trade_amount_usd_trans_no_median_diff_2', 'amt_3', 'date_cust_id_diff_3', 'amt_country_mean_3', 'amt_country_max_3', 'amt_country_min_3', 'amt_country_std_3', 'amt_country_var_3', 'amt_country_median_3', 'amt_country_median_diff_3', 'amt_cur_type_mean_3', 'amt_cur_type_max_3', 'amt_cur_type_min_3', 'amt_cur_type_std_3', 'amt_cur_type_var_3', 'amt_cur_type_median_3', 'amt_cur_type_median_diff_3', 'tx_time_cust_id_diff_3', 'tx_amt_exchg_3', 'tx_amt_exchg_tx_type_mean_3', 'tx_amt_exchg_tx_type_max_3', 'tx_amt_exchg_tx_type_min_3', 'tx_amt_exchg_tx_type_std_3', 'tx_amt_exchg_tx_type_var_3', 'tx_amt_exchg_tx_type_median_3', 'tx_amt_exchg_tx_type_median_diff_3', 'tx_amt_exchg_info_asset_code_mean_3', 'tx_amt_exchg_info_asset_code_max_3', 'tx_amt_exchg_info_asset_code_min_3', 'tx_amt_exchg_info_asset_code_std_3', 'tx_amt_exchg_info_asset_code_var_3', 'tx_amt_exchg_info_asset_code_median_3', 'tx_amt_exchg_info_asset_code_median_diff_3', 'tx_amt_exchg_fiscTxId_mean_3', 'tx_amt_exchg_fiscTxId_max_3', 'tx_amt_exchg_fiscTxId_min_3', 'tx_amt_exchg_fiscTxId_std_3', 'tx_amt_exchg_fiscTxId_var_3', 'tx_amt_exchg_fiscTxId_median_3', 'tx_amt_exchg_fiscTxId_median_diff_3', 'tx_amt_exchg_txbranch_mean_3', 'tx_amt_exchg_txbranch_max_3', 'tx_amt_exchg_txbranch_min_3', 'tx_amt_exchg_txbranch_std_3', 'tx_amt_exchg_txbranch_var_3', 'tx_amt_exchg_txbranch_median_3', 'tx_amt_exchg_txbranch_median_diff_3', 'trade_amount_usd_3', 'trans_date_cust_id_diff_3', 'trade_amount_usd_trans_no_mean_3', 'trade_amount_usd_trans_no_max_3', 'trade_amount_usd_trans_no_min_3', 'trade_amount_usd_trans_no_std_3', 'trade_amount_usd_trans_no_var_3', 'trade_amount_usd_trans_no_median_3', 'trade_amount_usd_trans_no_median_diff_3', 'amt_4', 'date_cust_id_diff_4', 'amt_country_mean_4', 'amt_country_max_4', 'amt_country_min_4', 'amt_country_std_4', 'amt_country_var_4', 'amt_country_median_4', 'amt_country_median_diff_4', 'amt_cur_type_mean_4', 'amt_cur_type_max_4', 'amt_cur_type_min_4', 'amt_cur_type_std_4', 'amt_cur_type_var_4', 'amt_cur_type_median_4', 'amt_cur_type_median_diff_4', 'tx_time_cust_id_diff_4', 'tx_amt_exchg_4', 'tx_amt_exchg_tx_type_mean_4', 'tx_amt_exchg_tx_type_max_4', 'tx_amt_exchg_tx_type_min_4', 'tx_amt_exchg_tx_type_std_4', 'tx_amt_exchg_tx_type_var_4', 'tx_amt_exchg_tx_type_median_4', 'tx_amt_exchg_tx_type_median_diff_4', 'tx_amt_exchg_info_asset_code_mean_4', 'tx_amt_exchg_info_asset_code_max_4', 'tx_amt_exchg_info_asset_code_min_4', 'tx_amt_exchg_info_asset_code_std_4', 'tx_amt_exchg_info_asset_code_var_4', 'tx_amt_exchg_info_asset_code_median_4', 'tx_amt_exchg_info_asset_code_median_diff_4', 'tx_amt_exchg_fiscTxId_mean_4', 'tx_amt_exchg_fiscTxId_max_4', 'tx_amt_exchg_fiscTxId_min_4', 'tx_amt_exchg_fiscTxId_std_4', 'tx_amt_exchg_fiscTxId_var_4', 'tx_amt_exchg_fiscTxId_median_4', 'tx_amt_exchg_fiscTxId_median_diff_4', 'tx_amt_exchg_txbranch_mean_4', 'tx_amt_exchg_txbranch_max_4', 'tx_amt_exchg_txbranch_min_4', 'tx_amt_exchg_txbranch_std_4', 'tx_amt_exchg_txbranch_var_4', 'tx_amt_exchg_txbranch_median_4', 'tx_amt_exchg_txbranch_median_diff_4', 'trade_amount_usd_4', 'trans_date_cust_id_diff_4', 'trade_amount_usd_trans_no_mean_4', 'trade_amount_usd_trans_no_max_4', 'trade_amount_usd_trans_no_min_4', 'trade_amount_usd_trans_no_std_4', 'trade_amount_usd_trans_no_var_4', 'trade_amount_usd_trans_no_median_4', 'trade_amount_usd_trans_no_median_diff_4', 'amt_5', 'date_cust_id_diff_5', 'amt_country_mean_5', 'amt_country_max_5', 'amt_country_min_5', 'amt_country_std_5', 'amt_country_var_5', 'amt_country_median_5', 'amt_country_median_diff_5', 'amt_cur_type_mean_5', 'amt_cur_type_max_5', 'amt_cur_type_min_5', 'amt_cur_type_std_5', 'amt_cur_type_var_5', 'amt_cur_type_median_5', 'amt_cur_type_median_diff_5', 'tx_time_cust_id_diff_5', 'tx_amt_exchg_5', 'tx_amt_exchg_tx_type_mean_5', 'tx_amt_exchg_tx_type_max_5', 'tx_amt_exchg_tx_type_min_5', 'tx_amt_exchg_tx_type_std_5', 'tx_amt_exchg_tx_type_var_5', 'tx_amt_exchg_tx_type_median_5', 'tx_amt_exchg_tx_type_median_diff_5', 'tx_amt_exchg_info_asset_code_mean_5', 'tx_amt_exchg_info_asset_code_max_5', 'tx_amt_exchg_info_asset_code_min_5', 'tx_amt_exchg_info_asset_code_std_5', 'tx_amt_exchg_info_asset_code_var_5', 'tx_amt_exchg_info_asset_code_median_5', 'tx_amt_exchg_info_asset_code_median_diff_5', 'tx_amt_exchg_fiscTxId_mean_5', 'tx_amt_exchg_fiscTxId_max_5', 'tx_amt_exchg_fiscTxId_min_5', 'tx_amt_exchg_fiscTxId_std_5', 'tx_amt_exchg_fiscTxId_var_5', 'tx_amt_exchg_fiscTxId_median_5', 'tx_amt_exchg_fiscTxId_median_diff_5', 'tx_amt_exchg_txbranch_mean_5', 'tx_amt_exchg_txbranch_max_5', 'tx_amt_exchg_txbranch_min_5', 'tx_amt_exchg_txbranch_std_5', 'tx_amt_exchg_txbranch_var_5', 'tx_amt_exchg_txbranch_median_5', 'tx_amt_exchg_txbranch_median_diff_5', 'trade_amount_usd_5', 'trans_date_cust_id_diff_5', 'trade_amount_usd_trans_no_mean_5', 'trade_amount_usd_trans_no_max_5', 'trade_amount_usd_trans_no_min_5', 'trade_amount_usd_trans_no_std_5', 'trade_amount_usd_trans_no_var_5', 'trade_amount_usd_trans_no_median_5', 'trade_amount_usd_trans_no_median_diff_5']
['risk_rank', 'occupation_code', 'AGE', 'country_1', 'cur_type_1', 'debit_credit_1', 'tx_type_1', 'info_asset_code_1', 'fiscTxId_1', 'txbranch_1', 'cross_bank_1', 'ATM_1', 'is_foreign_1', 'trans_no_1', 'country_2', 'cur_type_2', 'debit_credit_2', 'tx_type_2', 'info_asset_code_2', 'fiscTxId_2', 'txbranch_2', 'cross_bank_2', 'ATM_2', 'is_foreign_2', 'trans_no_2', 'country_3', 'cur_type_3', 'debit_credit_3', 'tx_type_3', 'info_asset_code_3', 'fiscTxId_3', 'txbranch_3', 'cross_bank_3', 'ATM_3', 'is_foreign_3', 'trans_no_3', 'country_4', 'cur_type_4', 'debit_credit_4', 'tx_type_4', 'info_asset_code_4', 'fiscTxId_4', 'txbranch_4', 'cross_bank_4', 'ATM_4', 'is_foreign_4', 'trans_no_4', 'country_5', 'cur_type_5', 'debit_credit_5', 'tx_type_5', 'info_asset_code_5', 'fiscTxId_5', 'txbranch_5', 'cross_bank_5', 'ATM_5', 'is_foreign_5', 'trans_no_5']

In [ ]:
#training_data, testing_data
def Simple_Missing_Value(df, df2):
    #數值補中位數, 非數值補最高頻率
    imp_median = SimpleImputer(missing_values=np.nan, strategy='median')
    imp_most_frequent = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
    for i in COL_NAME:
        if df[i].isnull().all() == True:
            arg = np.empty((len(df[i]),1))
        else:
            arg = np.array(df[i]).reshape([-1, 1])
        if df2[i].isnull().all() == True:
            arg2 = np.empty((len(df2[i]),1))
        else:
            arg2 = np.array(df2[i]).reshape([-1, 1])
  
        if i in numerical_column:
            imr = imp_median.fit(arg)
            df[i] = imr.transform(arg)
            df2[i] = imr.transform(arg2)
        if i in non_numerical_column:
            imr = imp_most_frequent.fit(arg)
            df[i] = imr.transform(arg)
            df2[i] = imr.transform(arg2)
    return df, df2

In [ ]:
df, df2 = Simple_Missing_Value(df, df2)
df.describe()

,risk_rank,occupation_code,total_asset,AGE,lupay,cycam,usgam,clamt,csamt,inamt,cucsm,cucah,country_1,cur_type_1,amt_1,date_cust_id_diff_1,date_cust_id_diff_cust_id_mean_1,amt_country_mean_1,amt_country_max_1,amt_country_min_1,amt_country_std_1,amt_country_var_1,amt_country_median_1,amt_country_median_diff_1,amt_cur_type_mean_1,amt_cur_type_max_1,amt_cur_type_min_1,amt_cur_type_std_1,amt_cur_type_var_1,amt_cur_type_median_1,amt_cur_type_median_diff_1,country_2,cur_type_2,amt_2,date_cust_id_diff_2,amt_country_mean_2,amt_country_max_2,amt_country_min_2,amt_country_std_2,amt_country_var_2,amt_country_median_2,amt_country_median_diff_2,amt_cur_type_mean_2,amt_cur_type_max_2,amt_cur_type_min_2,amt_cur_type_std_2,amt_cur_type_var_2,amt_cur_type_median_2,amt_cur_type_median_diff_2,country_3,cur_type_3,amt_3,date_cust_id_diff_3,amt_country_mean_3,amt_country_max_3,amt_country_min_3,amt_country_std_3,amt_country_var_3,amt_country_median_3,amt_country_median_diff_3,amt_cur_type_mean_3,amt_cur_type_max_3,amt_cur_type_min_3,amt_cur_type_std_3,amt_cur_type_var_3,amt_cur_type_median_3,amt_cur_type_median_diff_3,country_4,cur_type_4,amt_4,date_cust_id_diff_4,amt_country_mean_4,amt_country_max_4,amt_country_min_4,amt_country_std_4,amt_country_var_4,amt_country_median_4,amt_country_median_diff_4,amt_cur_type_mean_4,amt_cur_type_max_4,amt_cur_type_min_4,amt_cur_type_std_4,amt_cur_type_var_4,amt_cur_type_median_4,amt_cur_type_median_diff_4,country_5,cur_type_5,amt_5,date_cust_id_diff_5,amt_country_mean_5,amt_country_max_5,amt_country_min_5,amt_country_std_5,amt_country_var_5,amt_country_median_5,amt_country_median_diff_5,amt_cur_type_mean_5,amt_cur_type_max_5,amt_cur_type_min_5,amt_cur_type_std_5,amt_cur_type_var_5,amt_cur_type_median_5,amt_cur_type_median_diff_5,cdtx_trans_num,debit_credit_1,tx_type_1,info_asset_code_1,fiscTxId_1,txbranch_1,cross_bank_1,ATM_1,tx_time_cust_id_diff_1,tx_time_cust_id_diff_cust_id_mean_1,tx_amt_exchg_1,is_foreign_1,tx_amt_exchg_tx_type_mean_1,tx_amt_exchg_tx_type_max_1,tx_amt_exchg_tx_type_min_1,tx_amt_exchg_tx_type_std_1,tx_amt_exchg_tx_type_var_1,tx_amt_exchg_tx_type_median_1,tx_amt_exchg_tx_type_median_diff_1,tx_amt_exchg_info_asset_code_mean_1,tx_amt_exchg_info_asset_code_max_1,tx_amt_exchg_info_asset_code_min_1,tx_amt_exchg_info_asset_code_std_1,tx_amt_exchg_info_asset_code_var_1,tx_amt_exchg_info_asset_code_median_1,tx_amt_exchg_info_asset_code_median_diff_1,tx_amt_exchg_fiscTxId_mean_1,tx_amt_exchg_fiscTxId_max_1,tx_amt_exchg_fiscTxId_min_1,tx_amt_exchg_fiscTxId_std_1,tx_amt_exchg_fiscTxId_var_1,tx_amt_exchg_fiscTxId_median_1,tx_amt_exchg_fiscTxId_median_diff_1,tx_amt_exchg_txbranch_mean_1,tx_amt_exchg_txbranch_max_1,tx_amt_exchg_txbranch_min_1,tx_amt_exchg_txbranch_std_1,tx_amt_exchg_txbranch_var_1,tx_amt_exchg_txbranch_median_1,tx_amt_exchg_txbranch_median_diff_1,debit_credit_2,tx_type_2,info_asset_code_2,fiscTxId_2,txbranch_2,cross_bank_2,ATM_2,tx_time_cust_id_diff_2,tx_amt_exchg_2,is_foreign_2,tx_amt_exchg_tx_type_mean_2,tx_amt_exchg_tx_type_max_2,tx_amt_exchg_tx_type_min_2,tx_amt_exchg_tx_type_std_2,tx_amt_exchg_tx_type_var_2,tx_amt_exchg_tx_type_median_2,tx_amt_exchg_tx_type_median_diff_2,tx_amt_exchg_info_asset_code_mean_2,tx_amt_exchg_info_asset_code_max_2,tx_amt_exchg_info_asset_code_min_2,tx_amt_exchg_info_asset_code_std_2,tx_amt_exchg_info_asset_code_var_2,tx_amt_exchg_info_asset_code_median_2,tx_amt_exchg_info_asset_code_median_diff_2,tx_amt_exchg_fiscTxId_mean_2,tx_amt_exchg_fiscTxId_max_2,tx_amt_exchg_fiscTxId_min_2,tx_amt_exchg_fiscTxId_std_2,tx_amt_exchg_fiscTxId_var_2,tx_amt_exchg_fiscTxId_median_2,tx_amt_exchg_fiscTxId_median_diff_2,tx_amt_exchg_txbranch_mean_2,tx_amt_exchg_txbranch_max_2,tx_amt_exchg_txbranch_min_2,tx_amt_exchg_txbranch_std_2,tx_amt_exchg_txbranch_var_2,tx_amt_exchg_txbranch_median_2,tx_amt_exchg_txbranch_median_diff_2,debit_credit_3,tx_type_3,info_asset_code_3,fiscTxId_3,txbranch_3,cross_bank_3,ATM_3,tx_time_cust_id_diff_3,tx_amt_exchg_3,is_foreign_3,tx_amt_exchg_tx_type_mean_3,tx_amt_exchg_tx_type_max_3,tx_amt_exchg_tx_type_min_3,tx_amt_exchg_tx_type_std_3,tx_amt_exchg_tx_type_var_3,tx_amt_exchg_tx_type_median_3,tx_amt_exchg_tx_type_median_diff_3,tx_amt_exchg_info_asset_code_mean_3,tx_amt_exchg_info_asset_code_max_3,tx_amt_exchg_info_asset_code_min_3,tx_amt_exchg_info_asset_code_std_3,tx_amt_exchg_info_asset_code_var_3,tx_amt_exchg_info_asset_code_median_3,tx_amt_exchg_info_asset_code_median_diff_3,tx_amt_exchg_fiscTxId_mean_3,tx_amt_exchg_fiscTxId_max_3,tx_amt_exchg_fiscTxId_min_3,tx_amt_exchg_fiscTxId_std_3,tx_amt_exchg_fiscTxId_var_3,tx_amt_exchg_fiscTxId_median_3,tx_amt_exchg_fiscTxId_median_diff_3,tx_amt_exchg_txbranch_mean_3,tx_amt_exchg_txbranch_max_3,tx_amt_exchg_txbranch_min_3,tx_amt_exchg_txbranch_std_3,tx_amt_exchg_txbranch_var_3,tx_amt_exchg_txbranch_median_3,tx_amt_exchg_txbranch_median_diff_3,debit_credit_4,tx_type_4,info_asset_code_4,fiscTxId_4,txbranch_4,cross_bank_4,ATM_4,tx_time_cust_id_diff_4,tx_amt_exchg_4,is_foreign_4,tx_amt_exchg_tx_type_mean_4,tx_amt_exchg_tx_type_max_4,tx_amt_exchg_tx_type_min_4,tx_amt_exchg_tx_type_std_4,tx_amt_exchg_tx_type_var_4,tx_amt_exchg_tx_type_median_4,tx_amt_exchg_tx_type_median_diff_4,tx_amt_exchg_info_asset_code_mean_4,tx_amt_exchg_info_asset_code_max_4,tx_amt_exchg_info_asset_code_min_4,tx_amt_exchg_info_asset_code_std_4,tx_amt_exchg_info_asset_code_var_4,tx_amt_exchg_info_asset_code_median_4,tx_amt_exchg_info_asset_code_median_diff_4,tx_amt_exchg_fiscTxId_mean_4,tx_amt_exchg_fiscTxId_max_4,tx_amt_exchg_fiscTxId_min_4,tx_amt_exchg_fiscTxId_std_4,tx_amt_exchg_fiscTxId_var_4,tx_amt_exchg_fiscTxId_median_4,tx_amt_exchg_fiscTxId_median_diff_4,tx_amt_exchg_txbranch_mean_4,tx_amt_exchg_txbranch_max_4,tx_amt_exchg_txbranch_min_4,tx_amt_exchg_txbranch_std_4,tx_amt_exchg_txbranch_var_4,tx_amt_exchg_txbranch_median_4,tx_amt_exchg_txbranch_median_diff_4,debit_credit_5,tx_type_5,info_asset_code_5,fiscTxId_5,txbranch_5,cross_bank_5,ATM_5,tx_time_cust_id_diff_5,tx_amt_exchg_5,is_foreign_5,tx_amt_exchg_tx_type_mean_5,tx_amt_exchg_tx_type_max_5,tx_amt_exchg_tx_type_min_5,tx_amt_exchg_tx_type_std_5,tx_amt_exchg_tx_type_var_5,tx_amt_exchg_tx_type_median_5,tx_amt_exchg_tx_type_median_diff_5,tx_amt_exchg_info_asset_code_mean_5,tx_amt_exchg_info_asset_code_max_5,tx_amt_exchg_info_asset_code_min_5,tx_amt_exchg_info_asset_code_std_5,tx_amt_exchg_info_asset_code_var_5,tx_amt_exchg_info_asset_code_median_5,tx_amt_exchg_info_asset_code_median_diff_5,tx_amt_exchg_fiscTxId_mean_5,tx_amt_exchg_fiscTxId_max_5,tx_amt_exchg_fiscTxId_min_5,tx_amt_exchg_fiscTxId_std_5,tx_amt_exchg_fiscTxId_var_5,tx_amt_exchg_fiscTxId_median_5,tx_amt_exchg_fiscTxId_median_diff_5,tx_amt_exchg_txbranch_mean_5,tx_amt_exchg_txbranch_max_5,tx_amt_exchg_txbranch_min_5,tx_amt_exchg_txbranch_std_5,tx_amt_exchg_txbranch_var_5,tx_amt_exchg_txbranch_median_5,tx_amt_exchg_txbranch_median_diff_5,dp_trans_num,trans_no_1,trade_amount_usd_1,trans_date_cust_id_diff_1,trans_date_cust_id_diff_cust_id_mean_1,trade_amount_usd_trans_no_mean_1,trade_amount_usd_trans_no_max_1,trade_amount_usd_trans_no_min_1,trade_amount_usd_trans_no_std_1,trade_amount_usd_trans_no_var_1,trade_amount_usd_trans_no_median_1,trade_amount_usd_trans_no_median_diff_1,trans_no_2,trade_amount_usd_2,trans_date_cust_id_diff_2,trade_amount_usd_trans_no_mean_2,trade_amount_usd_trans_no_max_2,trade_amount_usd_trans_no_min_2,trade_amount_usd_trans_no_std_2,trade_amount_usd_trans_no_var_2,trade_amount_usd_trans_no_median_2,trade_amount_usd_trans_no_median_diff_2,trans_no_3,trade_amount_usd_3,trans_date_cust_id_diff_3,trade_amount_usd_trans_no_mean_3,trade_amount_usd_trans_no_max_3,trade_amount_usd_trans_no_min_3,trade_amount_usd_trans_no_std_3,trade_amount_usd_trans_no_var_3,trade_amount_usd_trans_no_median_3,trade_amount_usd_trans_no_median_diff_3,trans_no_4,trade_amount_usd_4,trans_date_cust_id_diff_4,trade_amount_usd_trans_no_mean_4,trade_amount_usd_trans_no_max_4,trade_amount_usd_trans_no_min_4,trade_amount_usd_trans_no_std_4,trade_amount_usd_trans_no_var_4,trade_amount_usd_trans_no_median_4,trade_amount_usd_trans_no_median_diff_4,trans_no_5,trade_amount_usd_5,trans_date_cust_id_diff_5,trade_amount_usd_trans_no_mean_5,trade_amount_usd_trans_no_max_5,trade_amount_usd_trans_no_min_5,trade_amount_usd_trans_no_std_5,trade_amount_usd_trans_no_var_5,trade_amount_usd_trans_no_median_5,trade_amount_usd_trans_no_median_diff_5,remit_trans_num
count,23906.0000,23906.0000,2.3906e+04,23906.0000,2.3906e+04,2.3906e+04,2.3906e+04,23906.0000,23906.0000,2.3906e+04,2.3906e+04,23906.0000,23906.0000,23906.0000,2.3906e+04,23906.0000,23906.0000,23906.0000,2.3906e+04,23906.0000,23906.0000,2.3906e+04,23906.0000,2.3906e+04,23906.0000,2.3906e+04,23906.0000,23906.0000,2.3906e+04,23906.0000,2.3906e+04,23906.0000,23906.0000,2.3906e+04,23906.0000,23906.0000,2.3906e+04,23906.0000,23906.0000,2.3906e+04,23906.0000,2.3906e+04,23906.0000,2.3906e+04,23906.0000,23906.0000,2.3906e+04,23906.0000,2.3906e+04,23906.0000,23906.0000,2.3906e+04,23906.0000,23906.0000,2.3906e+04,23906.0000,23906.0000,2.3906e+04,23906.0000,2.3906e+04,23906.0000,2.3906e+04,23906.0000,23906.0000,2.3906e+04,23906.0000,2.3906e+04,23906.0000,23906.0000,2.3906e+04,23906.0000,23906.0000,2.3906e+04,23906.0000,23906.0000,2.3906e+04,23906.0000,2.3906e+04,23906.0000,2.3906e+04,23906.0000,23906.0000,2.3906e+04,23906.000,2.3906e+04,23906.0000,23906.0000,2.3906e+04,23906.0000,23906.0000,2.3906e+04,23906.0000,23906.0000,2.3906e+04,23906.0000,2.3906e+04,23906.0000,2.3906e+04,23906.0000,23906.0000,2.3906e+04,23906.0000,2.3906e+04,23906.0000,23906.0000,23906.0000,23906.0000,23906.0000,23906.0000,23906.0000,23906.0000,23906.0000,23906.0000,2.3906e+04,23906.0000,23906.0000,2.3906e+04,2.3906e+04,2.3906e+04,2.3906e+04,23906.0000,2.3906e+04,2.3906e+04,2.3906e+04,2.3906e+04,2.3906e+04,2.3906e+04,23906.0000,2.3906e+04,2.3906e+04,2.3906e+04,2.3906e+04,2.3906e+04,2.3906e+04,23906.0000,2.3906e+04,2.3906e+04,2.3906e+04,2.3906e+04,2.3906e+04,2.3906e+04,23906.0000,2.3906e+04,23906.0000,23906.0000,23906.0000,23906.0000,23906.0000,23906.0000,23906.0000,23906.0000,2.3906e+04,23906.0000,23906.0000,2.3906e+04,2.3906e+04,2.3906e+04,2.3906e+04,23906.0000,2.3906e+04,2.3906e+04,2.3906e+04,2.3906e+04,2.3906e+04,2.3906e+04,23906.0000,2.3906e+04,2.3906e+04,2.3906e+04,2.3906e+04,2.3906e+04,2.3906e+04,23906.0000,2.3906e+04,2.3906e+04,2.3906e+04,2.3906e+04,2.3906e+04,2.3906e+04,23906.0000,2.3906e+04,23906.0000,23906.0000,23906.0000,23906.0000,23906.0000,23906.0000,23906.0000,23906.000,2.3906e+04,23906.0000,23906.0000,2.3906e+04,2.3906e+04,2.3906e+04,2.3906e+04,23906.0000,2.3906e+04,2.3906e+04,2.3906e+04,2.3906e+04,2.3906e+04,2.3906e+04,23906.0000,2.3906e+04,2.3906e+04,2.3906e+04,2.3906e+04,2.3906e+04,2.3906e+04,23906.0000,2.3906e+04,2.3906e+04,2.3906e+04,2.3906e+04,2.3906e+04,2.3906e+04,23906.0000,2.3906e+04,23906.0000,23906.0000,23906.0000,23906.000,23906.0000,23906.0000,23906.0000,23906.0000,2.3906e+04,23906.0000,23906.0000,2.3906e+04,2.3906e+04,2.3906e+04,2.3906e+04,23906.0000,2.3906e+04,2.3906e+04,2.3906e+04,2.3906e+04,2.3906e+04,2.3906e+04,23906.0000,2.3906e+04,2.3906e+04,2.3906e+04,2.3906e+04,2.3906e+04,2.3906e+04,23906.0000,2.3906e+04,2.3906e+04,2.3906e+04,2.3906e+04,2.3906e+04,2.3906e+04,23906.0000,2.3906e+04,23906.0000,23906.0000,23906.0000,23906.0000,23906.0000,23906.0000,23906.0000,23906.0000,2.3906e+04,23906.0000,23906.0000,2.3906e+04,2.3906e+04,2.3906e+04,2.3906e+04,23906.0000,2.3906e+04,2.3906e+04,2.3906e+04,2.3906e+04,2.3906e+04,2.3906e+04,23906.0000,2.3906e+04,2.3906e+04,2.3906e+04,2.3906e+04,2.3906e+04,2.3906e+04,23906.0000,2.3906e+04,2.3906e+04,2.3906e+04,2.3906e+04,2.3906e+04,2.3906e+04,23906.0000,2.3906e+04,23906.0000,23906.0000,2.3906e+04,23906.0000,23906.0000,23906.0000,2.3906e+04,23906.0000,23906.0000,2.3906e+04,23906.0000,2.3906e+04,23906.0000,2.3906e+04,23906.0000,23906.0000,2.3906e+04,23906.0000,23906.0000,2.3906e+04,23906.0000,2.3906e+04,23906.0000,2.3906e+04,23906.0000,23906.0000,2.3906e+04,23906.0000,23906.0000,2.3906e+04,23906.0000,2.3906e+04,23906.0000,2.3906e+04,23906.0000,23906.0000,2.3906e+04,23906.0000,23906.0000,2.3906e+04,23906.0000,2.3906e+04,23906.0000,2.3906e+04,23906.0000,23906.0000,2.3906e+04,23906.0000,23906.0000,2.3906e+04,23906.0000,2.3906e+04,23906.0000
mean,1.6183,14.2896,7.1944e+05,3.6444,4.6716e+05,2.7344e+05,7.0617e+04,102.8282,67.8246,5.7287e+03,4.3976e+05,216.0325,125.6585,46.4304,2.5112e+04,3.7310,3.4675,6699.8772,1.1679e+08,15.2595,180565.6043,3.4981e+10,606.3849,2.4499e+04,6377.7195,1.2263e+08,1.9752,179002.4955,3.3069e+10,535.9874,2.4575e+04,125.7369,46.4968,2.5134e+04,2.9672,6723.4762,1.1686e+08,13.5357,180658.8766,3.5000e+10,631.7898,2.4496e+04,6376.8673,1.2273e+08,0.0830,179125.6595,3.3092e+10,533.3983,2.4601e+04,125.7462,46.4897,1.6121e+04,2.4408,6670.9941,1.1696e+08,9.3056,180750.7877,3.5021e+10,591.0160,1.5515e+04,6360.5205,1.2281e+08,0.2283,179203.8423,3.3112e+10,525.1962,1.5591e+04,125.6105,46.4432,1.3553e+04,2.1154,6671.5064,1.1716e+08,10.6037,181042.8635,3.5082e+10,589.7199,1.2954e+04,6364.0199,1.2290e+08,2.2012,179317.7596,3.3137e+10,528.605,1.3022e+04,125.8367,46.4510,1.5020e+04,2.2192,6710.5569,1.1742e+08,20.6245,181383.5033,3.5160e+10,637.3772,1.4371e+04,6397.6349,1.2298e+08,0.2556,179476.5725,3.3167e+10,548.7754,1.4471e+04,2.8283,0.6075,1.8881,12.4657,6.5234,124.4852,0.1314,0.7481,76.2424,81.4816,6.3914e+05,0.1817,470279.0703,6.9833e+09,-2.5560e+08,1.2158e+07,1.6386e+14,5438.3788,6.3369e+05,7.0352e+05,1.9685e+09,-5.7800e+07,8.9196e+06,2.7696e+14,10962.2702,6.2793e+05,5.1896e+05,4.0561e+09,-2.2548e+08,1.2232e+07,2.0430e+14,6196.1727,6.3291e+05,5.8373e+05,1.5643e+09,-9.7181e+07,9.6608e+06,2.4705e+14,8814.1393,6.3028e+05,0.5712,1.9076,13.0046,6.6483,124.3221,0.1359,0.7555,40.4372,9.8061e+05,0.1999,466018.5047,6.8978e+09,-2.5249e+08,1.2020e+07,1.6186e+14,5435.2261,9.7513e+05,7.6119e+05,2.1079e+09,-6.3446e+07,9.5405e+06,3.0343e+14,11612.8646,9.6881e+05,5.2246e+05,4.0247e+09,-2.2477e+08,1.2127e+07,1.9932e+14,6243.0632,9.7427e+05,5.8961e+05,1.5264e+09,-9.2567e+07,9.6573e+06,2.5034e+14,8951.3334,9.7156e+05,0.6045,1.9000,12.8203,6.6672,122.0302,0.1426,0.7766,37.309,7.3893e+05,0.1742,465638.3116,6.8884e+09,-2.5214e+08,1.2005e+07,1.6163e+14,5442.9491,7.3347e+05,6.8218e+05,1.9392e+09,-5.6086e+07,8.6358e+06,2.6449e+14,10573.1345,7.2802e+05,5.2431e+05,4.0398e+09,-2.2498e+08,1.2195e+07,2.0175e+14,6253.5402,7.3264e+05,5.8857e+05,1.4933e+09,-8.8359e+07,9.5737e+06,2.4857e+14,8932.0989,7.2992e+05,0.6073,1.9073,12.7458,6.599,121.3123,0.1592,0.7868,37.6558,6.9655e+05,0.1599,466570.3138,6.9092e+09,-2.5291e+08,1.2038e+07,1.6213e+14,5433.8041,6.9111e+05,6.3331e+05,1.8394e+09,-5.1968e+07,8.0959e+06,2.4227e+14,10093.6676,6.8610e+05,5.2259e+05,4.0240e+09,-2.2573e+08,1.2092e+07,1.9695e+14,6219.2898,6.9029e+05,5.8671e+05,1.4861e+09,-8.7288e+07,9.5305e+06,2.3687e+14,8924.2985,6.8745e+05,0.5989,1.9017,12.5087,6.6049,120.5031,0.1639,0.7920,38.3897,5.2985e+05,0.1364,466404.4264,6.9047e+09,-2.5274e+08,1.2031e+07,1.6202e+14,5439.0326,5.2438e+05,5.6049e+05,1.6785e+09,-4.5517e+07,7.2587e+06,2.0757e+14,9376.1580,5.2002e+05,5.2252e+05,4.0306e+09,-2.2604e+08,1.2110e+07,1.9755e+14,6199.4727,5.2343e+05,5.6955e+05,1.4754e+09,-8.5699e+07,9.5411e+06,2.4737e+14,8862.2379,5.2065e+05,4.2104,0.1926,4.6074e+04,3.8746,5.8763,67337.5275,3.4325e+05,11.0395,67070.2061,4.7933e+09,49059.8427,9.3229e+03,0.1102,4.7080e+04,3.2834,67806.9336,3.0916e+05,10.6712,65698.1811,4.5004e+09,50000.2872,5.9353e+03,0.0842,4.8144e+04,2.7427,67965.2931,2.9783e+05,10.4976,65250.5622,4.3996e+09,50312.2384,4.4283e+03,0.0829,5.1334e+04,1.7937,67981.4388,2.9736e+05,10.4679,65237.7733,4.3957e+09,50333.7765,5.8036e+03,0.0843,5.0560e+04,1.6710,68018.8940,2.9904e+05,10.5231,65336.0038,4.4168e+09,50341.3017,6.0525e+03,1.1128
std,0.9096,4.6712,2.5031e+06,1.3120,1.8482e+06,1.1076e+06,6.8239e+05,3715.4531,7363.7553,8.5340e+04,1.6222e+06,8058.9560,18.3139,4.4041,3.4930e+05,13.4768,7.3849,4195.6147,3.5547e+07,1109.0804,48752.2662,1.0515e+10,4542.0430,3.4930e+05,2699.8922,2.4850e+07,292.5812,32049.1561,6.5636e+09,2011.7896,3.4930e+05,18.1097,4.1191,1.1804e+06,11.9385,4506.8539,3.5436e+07,1069.8470,48601.0188,1.0484e+10,4857.3690,1.1804e+06,2686.0262,2.4618e+07,3.2326,31725.3040,6.5081e+09,1990.9148,1.1804e+06,18.0192,4.1142,4.2101e+05,8.3462,3497.9090,3.5285e+07,873.6464,48477.7668,1.0453e+10,3724.3551,4.2099e+05,2281.0135,2.4429e+07,17.4431,31590.2157,6.4612e+09,1626.4418,4.2100e+05,18.3913,4.3418,2.5096e+05,5.6748,3443.5456,3.4978e+07,919.0853,48012.9497,1.0361e+10,3726.6762,2.5092e+05,2273.3477,2.4212e+07,293.3347,31336.1448,6.4048e+09,1652.458,2.5094e+05,17.9092,4.3082,3.8110e+05,7.2695,4884.8760,3.4600e+07,1377.3535,47539.3578,1.0243e+10,5833.5665,3.8106e+05,3341.9546,2.4005e+07,17.6957,30900.1366,6.3277e+09,2568.3716,3.8107e+05,2.4214,0.4883,0.3247,5.5318,6.0332,133.3440,0.3378,0.4341,331.8045,223.9487,7.2361e+06,0.3856,117822.8838,2.5236e+09,9.2706e+07,4.0071e+06,5.9399e+13,639.0249,7.2361e+06,1.1674e+06,2.8036e+09,1.0896e+08,1.4050e+07,5.7534e+14,12858.2726,7.2343e+06,1.7955e+05,1.7099e+09,1.1926e+08,7.3942e+06,3.3999e+14,3221.3492,7.2360e+06,8.3703e+05,1.3862e+09,1.2884e+08,1.2398e+07,2.4772e+15,9878.1979,7.2352e+06,0.4949,0.3469,5.3544,6.1258,132.8503,0.3427,0.4298,218.8586,1.9683e+07,0.3999,123141.3526,2.6223e+09,9.6245e+07,4.1683e+06,6.1708e+13,628.0740,1.9683e+07,1.2092e+06,2.8982e+09,1.1273e+08,1.4574e+07,5.9690e+14,13195.9316,1.9682e+07,1.8043e+05,1.7079e+09,1.1975e+08,7.2290e+06,3.3187e+14,3249.7798,1.9683e+07,8.4736e+05,1.3956e+09,1.2668e+08,1.2533e+07,2.5019e+15,9963.3190,1.9683e+07,0.4890,0.3465,5.2894,6.1531,132.5788,0.3497,0.4165,181.853,1.1205e+07,0.3793,123460.1364,2.6325e+09,9.6639e+07,4.1835e+06,6.1951e+13,638.9680,1.1205e+07,1.1445e+06,2.7351e+09,1.0674e+08,1.3781e+07,5.6491e+14,12732.8945,1.1204e+07,1.7992e+05,1.7054e+09,1.1959e+08,7.2827e+06,3.3549e+14,3251.6496,1.1205e+07,8.4772e+05,1.3899e+09,1.2483e+08,1.2527e+07,2.5020e+15,9850.2344,1.1204e+07,0.4884,0.3446,5.2153,6.081,132.4627,0.3659,0.4096,201.3101,1.2129e+07,0.3665,122505.6251,2.6095e+09,9.5779e+07,4.1477e+06,6.1407e+13,626.7536,1.2129e+07,1.1056e+06,2.6352e+09,1.0296e+08,1.3294e+07,5.4489e+14,12391.4675,1.2128e+07,1.7885e+05,1.6933e+09,1.1912e+08,7.1226e+06,3.2719e+14,3195.8446,1.2129e+07,8.2053e+05,1.3818e+09,1.2434e+08,1.2085e+07,2.3772e+15,9839.7123,1.2129e+07,0.4901,0.3440,5.2054,6.0827,132.6990,0.3701,0.4059,174.6166,5.6440e+06,0.3432,122614.2560,2.6144e+09,9.5974e+07,4.1548e+06,6.1525e+13,634.3211,5.6440e+06,1.0357e+06,2.4654e+09,9.6376e+07,1.2445e+07,5.0993e+14,11785.7909,5.6424e+06,1.7949e+05,1.6897e+09,1.1891e+08,7.1345e+06,3.2795e+14,3169.7689,5.6440e+06,8.4867e+05,1.3806e+09,1.2359e+08,1.2504e+07,2.5019e+15,9718.5733,5.6434e+06,1.7474,0.8092,5.3782e+04,14.1406,11.2570,6354.8173,3.8043e+05,9.1612,17171.2122,3.6571e+09,9342.6571,5.3803e+04,0.6182,4.4621e+04,9.2342,5379.0826,2.9733e+05,8.1748,13570.5413,2.8828e+09,7384.4576,4.4691e+04,0.5402,3.9674e+04,5.9729,4933.7825,2.6015e+05,6.8830,11914.2190,2.5257e+09,6568.7774,4.0385e+04,0.5366,3.8593e+04,5.2393,4868.1822,2.5828e+05,5.8269,11819.9274,2.5066e+09,6507.2449,3.9525e+04,0.5456,4.1950e+04,4.4356,4696.7493,2.6616e+05,5.9322,12165.6311,2.5895e+09,6492.5178,4.3133e+04,2.0146

In [ ]:
from google.colab import files
df.to_csv('training_data_xgboost_complete.csv') 
files.download('training_data_xgboost_complete.csv')

df2.to_csv('testing_data_xgboost_complete.csv') 
files.download('testing_data_xgboost_complete.csv')